using System;
using System.Globalization;
using System.Text;
using Ludots.Core.GraphRuntime;
using Ludots.Core.NodeLibraries.GASGraph;

namespace Ludots.Tests.Gas.Graph.Codegen
{
    /// <summary>
    /// R0 whitelist emitter: linear integer arithmetic IR → C#.
    /// Emits both a state-contract entry (<see cref="GeneratedMethodName"/>) and a tight
    /// locals entry (<see cref="GeneratedTightMethodName"/>) for microbench parity with handwritten C#.
    /// Unsupported ops fail closed (no silent omit).
    /// </summary>
    public static class LinearIntGraphCsharpEmitter
    {
        public const string GeneratedNamespace = "Ludots.Graph.Generated";
        public const string GeneratedTypeName = "GraphEntry";
        public const string GeneratedMethodName = "Execute";
        public const string GeneratedTightMethodName = "ExecuteLinearInt";

        public static string Emit(ReadOnlySpan<GraphInstruction> program, string assemblyMarker)
        {
            if (string.IsNullOrWhiteSpace(assemblyMarker))
            {
                throw new ArgumentException("assemblyMarker is required.", nameof(assemblyMarker));
            }

            var stateBody = new StringBuilder(program.Length * 48);
            var tightBody = new StringBuilder(program.Length * 40);
            int resultRegister = 0;
            bool sawWrite = false;

            for (int i = 0; i < program.Length; i++)
            {
                ref readonly GraphInstruction ins = ref program[i];
                GraphNodeOp op = (GraphNodeOp)ins.Op;
                switch (op)
                {
                    case GraphNodeOp.None:
                        continue;
                    case GraphNodeOp.ConstInt:
                        stateBody.Append("            state.I[")
                            .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                            .Append("] = ")
                            .Append(ins.Imm.ToString(CultureInfo.InvariantCulture))
                            .AppendLine(";");
                        tightBody.Append("        int r")
                            .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                            .Append(" = ")
                            .Append(ins.Imm.ToString(CultureInfo.InvariantCulture))
                            .AppendLine(";");
                        resultRegister = ins.Dst;
                        sawWrite = true;
                        break;
                    case GraphNodeOp.AddInt:
                        stateBody.Append("            state.I[")
                            .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                            .Append("] = state.I[")
                            .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                            .Append("] + state.I[")
                            .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                            .AppendLine("];");
                        tightBody.Append("        int r")
                            .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                            .Append(" = r")
                            .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                            .Append(" + r")
                            .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                            .AppendLine(";");
                        resultRegister = ins.Dst;
                        sawWrite = true;
                        break;
                    default:
                        throw new InvalidOperationException(
                            $"R0 linear codegen rejects unsupported op '{op}' at instruction index {i}. " +
                            "Only ConstInt/AddInt (and None) are whitelisted; widen via explicit emitter work, not silent skip.");
                }
            }

            var source = new StringBuilder(768 + stateBody.Length + tightBody.Length);
            source.AppendLine("// <auto-generated />");
            source.AppendLine("#nullable enable");
            source.AppendLine("using Ludots.Core.NodeLibraries.GASGraph;");
            source.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
            source.AppendLine();
            source.Append("public static class ").Append(GeneratedTypeName).AppendLine();
            source.AppendLine("{");
            source.Append("    public const string AssemblyMarker = \"")
                .Append(EscapeForCSharpString(assemblyMarker))
                .AppendLine("\";");
            source.Append("    public static void ").Append(GeneratedMethodName)
                .AppendLine("(ref GraphExecutionState state)");
            source.AppendLine("    {");
            if (stateBody.Length == 0)
            {
                source.AppendLine("        // empty program");
            }
            else
            {
                source.Append(stateBody);
            }

            source.AppendLine("    }");
            source.AppendLine();
            source.Append("    public static int ").Append(GeneratedTightMethodName).AppendLine("()");
            source.AppendLine("    {");
            if (!sawWrite)
            {
                source.AppendLine("        return 0;");
            }
            else
            {
                source.Append(tightBody);
                source.Append("        return r")
                    .Append(resultRegister.ToString(CultureInfo.InvariantCulture))
                    .AppendLine(";");
            }

            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private static string EscapeForCSharpString(string value)
        {
            return value
                .Replace("\\", "\\\\", StringComparison.Ordinal)
                .Replace("\"", "\\\"", StringComparison.Ordinal);
        }
    }
}
