#!/usr/bin/env python3
"""Sango terrain asset baker (M3.b).

Bakes the map-first terrain material set from the two SangoTerrainMod derived
binaries (regenerated by SangoTerrainExporter from the local DefaultMap.bin):

  * assets/Textures/terrain_control_weights.png  RGBA8, R/G/B/A = sand/grass/dirt/rock
    weights sampled per world position by the raylib continuous-heightmap shader
    (terrain.fs SampleControlWeights; UV = worldPos.xz over the CHTM bounds).
  * assets/Textures/terrain_{sand,grass,dirt,rock}.png  procedural tiling albedo
    layers (multi-octave value noise; no KOEI-derived pixels).

All tuning lives in sango_terrain_weight_rules.json next to this script; this
file only implements the contract. Deterministic: the noise seed is fixed by the
rules file. Outputs are derived binaries and stay untracked (repo .gitignore).

Usage (repo root):
  python mods/sango/SangoTerrainMod/assets/terrain/bake_terrain_assets.py
"""

from __future__ import annotations

import json
import math
import os
import struct
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
MOD_ASSETS = os.path.dirname(HERE)  # .../SangoTerrainMod/assets


def read_rules() -> dict:
    with open(os.path.join(HERE, "sango_terrain_weight_rules.json"), encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------- CHTM reader

def read_chtm(path: str):
    """Parse ContinuousHeightmapBinary v2 single-layer int16-cm assets.

    Layout (LE): 'CHTM', version, bounds(x,y,w,h), sampleColumns, sampleRows,
    storageLayout, defaultLayerIndex, interpolationMode, sampleScale(offset,
    num, den), layerCount, per-layer (id, name(len-prefixed str), offset,
    count), sampleCount, int16 samples row-major (row = north, col = east).
    """
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"CHTM":
        raise ValueError("not a CHTM file")
    version, bx, by, bw, bh, cols, rows, layout, default_layer, interp = struct.unpack_from(
        "<10i", data, 4)
    if version not in (1, 2):
        raise ValueError(f"unsupported CHTM version {version}")
    off = 44
    if version >= 2:
        off += 12  # sampleScale triple
    (layer_count,) = struct.unpack_from("<i", data, off)
    off += 4
    for _ in range(layer_count):
        (layer_id,) = struct.unpack_from("<i", data, off)
        off += 4
        (name_len,) = struct.unpack_from("<B", data, off)
        off += 1 + name_len
        off += 8  # sampleOffset + sampleCount
    (sample_count,) = struct.unpack_from("<i", data, off)
    off += 4
    expected = cols * rows
    if sample_count != expected:
        raise ValueError(f"CHTM sample count {sample_count} != {cols}x{rows}")
    samples = struct.unpack_from(f"<{sample_count}h", data, off)
    return {
        "bounds": (bx, by, bw, bh),
        "cols": cols,
        "rows": rows,
        "samples": samples,  # index = row * cols + col; row = north, col = east
    }


# ---------------------------------------------------------------- HEXM reader

CHUNK_SIZE = 64
TOTAL_CELLS = CHUNK_SIZE * CHUNK_SIZE
CLIFF_BYTES = TOTAL_CELLS * 3 // 8  # 3 edges/cell * 1 bit (VertexChunk.Derived*)


def read_hexm_terrain_types(path: str):
    """Parse VertexMapBinary v2 and return the extraByte layer-0 grid (256x256).

    Per chunk (cy outer, cx inner): packed[TOTAL], layer2[TOTAL],
    flags[512], ramps[512], factions[TOTAL], extraFlags0..2[512 each],
    extraBytes0[TOTAL] (index = local_row * 64 + local_col), cliff[1536].
    VertexMap col = east axis, row = north axis.
    """
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"HEXM":
        raise ValueError("not a HEXM file")
    version, width_chunks, height_chunks, chunk_size, _reserved = struct.unpack_from("<5i", data, 4)
    if version != 2 or chunk_size != CHUNK_SIZE:
        raise ValueError(f"unsupported HEXM header v{version} chunk {chunk_size}")
    cells_x = width_chunks * CHUNK_SIZE
    cells_y = height_chunks * CHUNK_SIZE
    types = bytearray(cells_x * cells_y)
    chunk_stride = (
        TOTAL_CELLS  # packed
        + TOTAL_CELLS  # layer2
        + 512 + 512  # flags, ramps
        + TOTAL_CELLS  # factions
        + 512 * 3  # extraFlags0..2
        + TOTAL_CELLS  # extraBytes0
        + CLIFF_BYTES
    )
    expected_size = 24 + width_chunks * height_chunks * chunk_stride
    if len(data) != expected_size:
        raise ValueError(
            f"HEXM size {len(data)} != expected {expected_size} "
            f"({width_chunks}x{height_chunks} chunks, stride {chunk_stride})")
    extra_offset_in_chunk = TOTAL_CELLS * 3 + 512 * 2 + 512 * 3
    base = 24
    for cy in range(height_chunks):
        for cx in range(width_chunks):
            chunk_index = cy * width_chunks + cx
            chunk_base = base + chunk_index * chunk_stride
            extra_base = chunk_base + extra_offset_in_chunk
            for local_row in range(CHUNK_SIZE):
                row = cy * CHUNK_SIZE + local_row
                src = extra_base + local_row * CHUNK_SIZE
                dst = row * cells_x + cx * CHUNK_SIZE
                types[dst:dst + CHUNK_SIZE] = data[src:src + CHUNK_SIZE]
    return cells_x, cells_y, types


# ---------------------------------------------------------------- noise

class ValueNoise:
    """Seeded 2D value noise with bilinear interpolation and octaves."""

    def __init__(self, seed: int):
        self._state = seed & 0xFFFFFFFF

    def _rand(self) -> float:
        self._state = (1103515245 * self._state + 12345) & 0x7FFFFFFF
        return self._state / float(0x7FFFFFFF)

    def _hash_grid(self, size: int):
        table = [[self._rand() for _ in range(size + 1)] for _ in range(size + 1)]
        return table

    def sample_octaves(self, x: float, y: float, frequency: float, octaves: int) -> float:
        amp = 1.0
        total = 0.0
        norm = 0.0
        for octave in range(octaves):
            f = frequency * (2 ** octave)
            total += amp * self._value(x * f, y * f)
            norm += amp
            amp *= 0.5
        return total / norm

    def _value(self, u: float, v: float) -> float:
        # Period-1 lattice so the albedo textures tile seamlessly.
        iu, iv = math.floor(u), math.floor(v)
        fu, fv = u - iu, v - iv
        sx = fu * fu * (3 - 2 * fu)
        sy = fv * fv * (3 - 2 * fv)
        n = lambda a, b: self._lattice_hash(iu + a, iv + b)
        top = n(0, 0) * (1 - sx) + n(1, 0) * sx
        bot = n(0, 1) * (1 - sx) + n(1, 1) * sx
        return top * (1 - sy) + bot * sy

    def _lattice_hash(self, ix: int, iy: int) -> float:
        h = (ix * 374761393 + iy * 668265263 + self._state) & 0xFFFFFFFF
        h = ((h ^ (h >> 13)) * 1274126177) & 0xFFFFFFFF
        return ((h ^ (h >> 16)) & 0xFFFF) / 65535.0


def smoothstep(edge0: float, edge1: float, x: float) -> float:
    if edge0 == edge1:
        return 0.0 if x < edge0 else 1.0
    t = max(0.0, min(1.0, (x - edge0) / (edge1 - edge0)))
    return t * t * (3 - 2 * t)


def band_weight(band: dict, h: float) -> float:
    rise = smoothstep(band["riseStart"], band["riseEnd"], h)
    fall = 1.0 - smoothstep(band["fallStart"], band["fallEnd"], h)
    return rise * fall


# ---------------------------------------------------------------- bake

def bake_control_map(rules: dict, chtm: dict, cells_x: int, cells_y: int, types) -> Image.Image:
    columns = rules["output"]["columns"]
    rows_n = rules["output"]["rows"]
    sea = float(rules["seaLevelCm"])
    peak = float(rules["peakSpanCm"])
    mod = rules["heightSlopeModulation"]
    bands = mod["bands"]
    slope_cfg = mod["slope"]
    noise_cfg = mod["noise"]
    type_mix = float(mod["typeBaseMix"])

    # Per-type base weights, precomputed lists indexed by terrain byte 0..255.
    base = {}
    for key, entry in rules["terrainTypeWeights"].items():
        base[int(key)] = (entry["sand"], entry["grass"], entry["dirt"], entry["rock"])
    default_base = base[21]

    # Per-cell type field is nearest-sampled then softened by a small blur on
    # the final image (blurCells), so material edges stay readable, not tiled.
    blur_cells = float(mod["cellSmoothing"]["blurCells"])
    blur_radius = max(1, int(round(blur_cells * columns / cells_x)))

    # Height lookup at control-map resolution (CHTM bilinear via nearest for
    # slope; bilinear for band value).
    hcols, hrows, hsamples = chtm["cols"], chtm["rows"], chtm["samples"]

    def height_at(px: int, py: int) -> float:
        u = px / (columns - 1) * (hcols - 1)
        v = py / (rows_n - 1) * (hrows - 1)
        x0, y0 = int(u), int(v)
        x1, y1 = min(x0 + 1, hcols - 1), min(y0 + 1, hrows - 1)
        fx, fy = u - x0, v - y0
        h00 = hsamples[y0 * hcols + x0]
        h10 = hsamples[y0 * hcols + x1]
        h01 = hsamples[y1 * hcols + x0]
        h11 = hsamples[y1 * hcols + x1]
        return (h00 * (1 - fx) * (1 - fy) + h10 * fx * (1 - fy)
                + h01 * (1 - fx) * fy + h11 * fx * fy)

    heights = [[0.0] * columns for _ in range(rows_n)]
    for py in range(rows_n):
        row = heights[py]
        for px in range(columns):
            row[px] = height_at(px, py)

    def slope_at(px: int, py: int) -> float:
        # 0..1 rough proxy: max abs central difference over one cell step (2000cm).
        step = max(1, columns // cells_x)
        h = heights[py][px]
        hx = heights[py][min(px + step, columns - 1)] - h
        hy = heights[min(py + step, rows_n - 1)][px] - h
        return min(1.0, math.hypot(hx, hy) / 1600.0)

    noise = ValueNoise(noise_cfg["seed"])
    freq = float(noise_cfg["frequency"])
    amp = float(noise_cfg["amplitude"])
    octaves = int(noise_cfg["octaves"])

    rgba = bytearray(columns * rows_n * 4)
    type_hits = {}
    for py in range(rows_n):
        v = py / (rows_n - 1)
        for px in range(columns):
            u = px / (columns - 1)
            cx = min(cells_x - 1, int(u * cells_x))
            cy = min(cells_y - 1, int(v * cells_y))
            t = types[cy * cells_x + cx]
            type_hits[t] = type_hits.get(t, 0) + 1
            tb = base.get(t, default_base)

            hcm = heights[py][px]
            hband = (hcm - sea) / peak
            slope = slope_at(px, py)
            n = noise.sample_octaves(u * 32.0, v * 32.0, freq, octaves)

            # Continuous modulation (east-asia style bands + slope).
            m_sand = band_weight(bands["sand"], hband)
            m_grass = band_weight(bands["grass"], hband) * max(0.0, 1.0 - slope * slope_cfg["grassDamp"])
            m_dirt = band_weight(bands["dirt"], hband)
            m_rock = band_weight(bands["rock"], hband) + (slope ** slope_cfg["rockBoostPower"]) * smoothstep(
                slope_cfg["rockBoostRise"], 1.0, slope)

            w = [
                max(0.0, tb[0] * type_mix + m_sand * (1 - type_mix)),
                max(0.0, tb[1] * type_mix + m_grass * (1 - type_mix)),
                max(0.0, tb[2] * type_mix + m_dirt * (1 - type_mix)),
                max(0.0, tb[3] * type_mix + m_rock * (1 - type_mix)),
            ]
            # Noise perturbs the mix without breaking normalization.
            w[0] *= 1.0 - amp * 0.5 + amp * n
            w[1] *= 1.0 - amp * 0.5 + amp * (1.0 - n)
            w[2] *= 1.0 - amp * 0.5 + amp * abs(n - 0.5) * 2.0
            s = sum(w) or 1e-5
            w = [x / s for x in w]

            o = (py * columns + px) * 4
            rgba[o] = int(w[0] * 255 + 0.5)
            rgba[o + 1] = int(w[1] * 255 + 0.5)
            rgba[o + 2] = int(w[2] * 255 + 0.5)
            rgba[o + 3] = int(w[3] * 255 + 0.5)

    # Soft pass over the type lattice is implicit via bilinear height/noise;
    # report coverage so missing types are visible in bake logs.
    covered = sorted(type_hits.keys())
    print(f"[bake] terrain types present: {covered}")
    print(f"[bake] dominant types: {sorted(type_hits.items(), key=lambda kv: -kv[1])[:8]}")
    img = Image.frombytes("RGBA", (columns, rows_n), bytes(rgba))

    if blur_radius > 1:
        # A small box blur only over material transitions keeps cell edges soft.
        from PIL import ImageFilter
        img = img.filter(ImageFilter.GaussianBlur(radius=blur_radius * 0.5))

    lattice = rules.get("hexLattice", {"enabled": False})
    if lattice.get("enabled"):
        img = apply_hex_lattice(img, lattice, cells_x)
    return img


def apply_hex_lattice(img: Image.Image, lattice: dict, cells: int) -> Image.Image:
    """Stamp the odd-r cell lattice onto the control weights.

    Matches VertexMapHexLayout's world contract: cell (c, r) spans
    [Left + c*cell (+cell/2 when r is odd), +cell] east and
    [Top + r*cell, +cell] north, so borders land where the engine's hex
    visual grid sits. terrain.fs samples this map raw (no anti-tile), so the
    lattice is what makes the full-map cell grid readable at overview range.
    """
    columns, rows_n = img.size
    border = float(lattice["borderMeters"]) / float(lattice["cellMeters"])
    strength = float(lattice["borderStrength"])
    line = (
        float(lattice["lineMixSand"]),
        float(lattice["lineMixGrass"]),
        float(lattice["lineMixDirt"]),
        float(lattice["lineMixRock"]),
    )
    checker = float(lattice["checkerAmplitude"])
    px = img.load()
    for py in range(rows_n):
        fz = (py + 0.5) / rows_n * cells
        r = int(fz)
        zfrac = fz - r
        row_shift = 0.5 if (r & 1) else 0.0
        for xp in range(columns):
            fu = (xp + 0.5) / columns * cells - row_shift
            c = int(fu)
            xfrac = fu - c
            on_border = xfrac < border or xfrac > 1.0 - border or zfrac < border or zfrac > 1.0 - border
            if on_border:
                w = px[xp, py]
                px[xp, py] = (
                    int((w[0] / 255.0) * (1.0 - strength) + line[0] * strength * 255.0 + 0.5),
                    int((w[1] / 255.0) * (1.0 - strength) + line[1] * strength * 255.0 + 0.5),
                    int((w[2] / 255.0) * (1.0 - strength) + line[2] * strength * 255.0 + 0.5),
                    int((w[3] / 255.0) * (1.0 - strength) + line[3] * strength * 255.0 + 0.5),
                )
            elif checker > 0.0 and ((c + r) & 1) == 0:
                w = px[xp, py]
                top = max(range(4), key=lambda i: w[i])
                boosted = [(w[i] / 255.0) * (1.0 + checker) if i == top else (w[i] / 255.0) * (1.0 - checker / 3.0) for i in range(4)]
                s = sum(boosted) or 1e-5
                px[xp, py] = tuple(int(x / s * 255.0 + 0.5) for x in boosted)
    return img


def bake_albedo_texture(spec: dict, seed: int) -> Image.Image:
    size = int(spec.get("size", 256))
    lr, lg, lb = spec["base"]
    amplitude = float(spec["amplitude"])
    frequency = float(spec["frequency"])
    octaves = int(spec["octaves"])
    grain = int(spec.get("grain", 0))
    noise = ValueNoise(seed)
    grain_noise = ValueNoise(seed ^ 0x5EED)
    img = Image.new("RGB", (size, size))
    px = img.load()
    for y in range(size):
        for x in range(size):
            u, v = x / size, y / size
            n = noise.sample_octaves(u, v, frequency, octaves) * 2.0 - 1.0
            g = (grain_noise.sample_octaves(x / size, y / size, 0.9, 1) * 2.0 - 1.0) * grain if grain else 0.0
            d = n * amplitude + g
            px[x, y] = (
                max(0, min(255, int(lr + d))),
                max(0, min(255, int(lg + d))),
                max(0, min(255, int(lb + d))),
            )
    return img


def main() -> int:
    rules = read_rules()
    src = rules["sources"]
    chtm = read_chtm(os.path.join(MOD_ASSETS, src["heightmap"].split("assets/", 1)[1]))
    cells_x, cells_y, types = read_hexm_terrain_types(os.path.join(MOD_ASSETS, src["hexGrid"].split("assets/", 1)[1]))
    print(f"[bake] CHTM {chtm['cols']}x{chtm['rows']} bounds={chtm['bounds']}; hex {cells_x}x{cells_y}")
    if cells_x != 256 or cells_y != 256:
        print(f"[bake] WARNING: expected 256x256 hex cells, got {cells_x}x{cells_y}", file=sys.stderr)

    textures_dir = os.path.join(MOD_ASSETS, "Textures")
    os.makedirs(textures_dir, exist_ok=True)

    control = bake_control_map(rules, chtm, cells_x, cells_y, types)
    control_path = os.path.join(MOD_ASSETS, rules["output"]["controlMap"].split("assets/", 1)[1])
    control.save(control_path, optimize=True)
    print(f"[bake] control map -> {control_path} ({control.width}x{control.height})")

    seed = int(rules["heightSlopeModulation"]["noise"]["seed"])
    for name, spec in rules["albedoTextures"]["layers"].items():
        tex = bake_albedo_texture(spec, seed)
        path = os.path.join(MOD_ASSETS, spec["file"].split("assets/", 1)[1])
        tex.save(path, optimize=True)
        print(f"[bake] albedo {name} -> {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
