using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("PersistenceTests")]
[assembly: InternalsVisibleTo("PresentationTests")]
[assembly: InternalsVisibleTo("ArchitectureTests")]
[assembly: InternalsVisibleTo("GasTests")]
[assembly: InternalsVisibleTo("CapabilityStandardScriptFlowSandboxMod")]
[assembly: InternalsVisibleTo("CapabilityStandardLiveSkillWorkbenchShowcaseMod")]
[assembly: InternalsVisibleTo("CapabilityStandardGraphOpsQueryMod")]
[assembly: InternalsVisibleTo("CapabilityStandardGraphOpsScriptMod")]
[assembly: InternalsVisibleTo("CapabilityStandardGraphOpsRelMod")]
[assembly: InternalsVisibleTo("CapabilityStandardGraphOpsNodeGalleryMod")]
[assembly: InternalsVisibleTo("CapabilityStandardGraphOpsFloatMod")]
[assembly: InternalsVisibleTo("CapabilityStandardGraphOpsAttrMod")]
[assembly: InternalsVisibleTo("CapabilityStandardGraphOpsBlackboardMod")]
[assembly: InternalsVisibleTo("CapabilityStandardGraphOpsEventMod")]
