<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Ludots.DataSchemaWorkbench</AssemblyName>
    <RootNamespace>ConfigurableDataSchemaSharedMod</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Ludots.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Ludots.UI\Ludots.UI.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
