using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Ludots.Core.GraphRuntime;
using Ludots.Core.NodeLibraries.GASGraph;

namespace Ludots.Graph.Codegen
{
    /// <summary>
    /// Emits C# for a lowered <see cref="GraphInstruction"/> program.
    /// Specialize path (F0–F3, back-edges allowed) when every op is specialize-capable;
    /// otherwise HandlerForward to <see cref="GasGraphOpHandlerTable.Instance"/> (fail-closed, no silent omit).
    /// </summary>
    public static class GraphCsharpEmitter
    {
        public const string GeneratedNamespace = "Ludots.Graph.Generated";
        public const string GeneratedTypeName = "GraphEntry";
        public const string GeneratedMethodName = "Execute";
        public const string GeneratedTightMethodName = "ExecuteLinearInt";

        public static GraphCodegenEmitResult Emit(
            ReadOnlySpan<GraphInstruction> program,
            string assemblyMarker,
            string[]? symbols = null,
            IReadOnlyList<string>? sourceNodeIds = null,
            bool forceHandlerForward = false)
        {
            if (string.IsNullOrWhiteSpace(assemblyMarker))
            {
                throw new ArgumentException("assemblyMarker is required.", nameof(assemblyMarker));
            }

            GraphCodegenEligibilityReport eligibility = GraphCodegenEligibility.Analyze(program, sourceNodeIds);
            var diagnostics = new List<string>();
            if (!eligibility.Eligible)
            {
                foreach (GraphCodegenUnsupportedOp item in eligibility.UnsupportedOps)
                {
                    diagnostics.Add(
                        $"unsupported op '{item.Op}' at instruction {item.InstructionIndex}" +
                        (item.NodeId == null ? "" : $" (node {item.NodeId})") +
                        $": {item.Reason}");
                }

                throw new InvalidOperationException(
                    "Graph codegen rejected the program (fail-closed): " + string.Join("; ", diagnostics));
            }

            bool useSpecialize = !forceHandlerForward &&
                                 string.Equals(eligibility.EmitMode, "specialize", StringComparison.Ordinal);
            if (useSpecialize && NeedsSymbols(program) && (symbols == null || symbols.Length == 0))
            {
                throw new InvalidOperationException(
                    "Specialize emit for ConstText requires a non-empty symbols table (fail-closed).");
            }

            bool emitTight = useSpecialize && IsF0Only(program);
            string source = useSpecialize
                ? EmitSpecialize(program, assemblyMarker, symbols, emitTight)
                : EmitHandlerForward(program, assemblyMarker);

            return new GraphCodegenEmitResult
            {
                Source = source,
                Eligibility = eligibility with { EmitMode = useSpecialize ? "specialize" : "handler-forward" },
                Diagnostics = diagnostics,
                UsesSpecialize = useSpecialize,
                EmitsTightEntry = emitTight,
            };
        }

        /// <summary>Spike-compatible wrapper: emit source string or throw.</summary>
        public static string EmitSource(ReadOnlySpan<GraphInstruction> program, string assemblyMarker) =>
            Emit(program, assemblyMarker).Source;

        private static bool NeedsSymbols(ReadOnlySpan<GraphInstruction> program)
        {
            for (int i = 0; i < program.Length; i++)
            {
                if ((GraphNodeOp)program[i].Op == GraphNodeOp.ConstText)
                {
                    return true;
                }
            }

            return false;
        }

        private static bool IsF0Only(ReadOnlySpan<GraphInstruction> program)
        {
            for (int i = 0; i < program.Length; i++)
            {
                GraphNodeOp op = (GraphNodeOp)program[i].Op;
                if (op == GraphNodeOp.None)
                {
                    continue;
                }

                if (!GraphCodegenStrategyCatalog.TryGet(op, out GraphCodegenStrategy strategy) ||
                    strategy.Family != GraphCodegenFamily.F0)
                {
                    return false;
                }
            }

            return true;
        }

        private static string EmitHandlerForward(ReadOnlySpan<GraphInstruction> program, string assemblyMarker)
        {
            var sb = new StringBuilder(512 + program.Length * 48);
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Ludots.Core.GraphRuntime;");
            sb.AppendLine("using Ludots.Core.NodeLibraries.GASGraph;");
            sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
            sb.AppendLine();
            sb.Append("public static class ").Append(GeneratedTypeName).AppendLine();
            sb.AppendLine("{");
            sb.Append("    public const string AssemblyMarker = \"")
                .Append(EscapeForCSharpString(assemblyMarker))
                .AppendLine("\";");
            sb.AppendLine("    public const string EmitMode = \"handler-forward\";");
            sb.AppendLine("    private static readonly GraphInstruction[] Instructions = new GraphInstruction[]");
            sb.AppendLine("    {");
            for (int i = 0; i < program.Length; i++)
            {
                AppendInstructionLiteral(sb, program[i], indent: "        ");
                sb.AppendLine(",");
            }

            sb.AppendLine("    };");
            sb.AppendLine();
            sb.Append("    public static void ").Append(GeneratedMethodName)
                .AppendLine("(ref GraphExecutionState state)");
            sb.AppendLine("    {");
            sb.AppendLine("        GasGraphOpHandlerTable.Instance.RunToHalt(ref state, Instructions);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string EmitSpecialize(
            ReadOnlySpan<GraphInstruction> program,
            string assemblyMarker,
            string[]? symbols,
            bool emitTight)
        {
            var usedInt = new SortedSet<int>();
            var usedBool = new SortedSet<int>();
            int resultRegister = 0;
            bool sawIntWrite = false;
            bool needsText = false;

            for (int i = 0; i < program.Length; i++)
            {
                ref readonly GraphInstruction ins = ref program[i];
                GraphNodeOp op = (GraphNodeOp)ins.Op;
                CollectSpecializeUses(op, ins, usedInt, usedBool, ref resultRegister, ref sawIntWrite, ref needsText);
                if (op is GraphNodeOp.Jump or GraphNodeOp.JumpIfFalse)
                {
                    _ = ResolveJumpTarget(i, ins.Imm, program.Length);
                }
            }

            var stateBody = new StringBuilder(program.Length * 80);
            var tightBody = emitTight ? new StringBuilder(program.Length * 56) : null;

            if (needsText)
            {
                stateBody.AppendLine("        if (state.Text == null)");
                stateBody.AppendLine("        {");
                stateBody.AppendLine("            state.Text = GraphTextHeap.ForCurrentThread();");
                stateBody.AppendLine("        }");
                stateBody.AppendLine();
            }

            for (int i = 0; i < program.Length; i++)
            {
                string label = LabelName(i);
                stateBody.Append("        ").Append(label).AppendLine(":");
                tightBody?.Append("        ").Append(label).AppendLine(":");

                ref readonly GraphInstruction ins = ref program[i];
                AppendSpecializeInstruction(stateBody, tightBody, i, ins, program.Length);
            }

            stateBody.Append("        ").Append(LabelName(program.Length)).AppendLine(":");
            stateBody.AppendLine("            ;");
            if (tightBody != null)
            {
                tightBody.Append("        ").Append(LabelName(program.Length)).AppendLine(":");
                if (!sawIntWrite)
                {
                    tightBody.AppendLine("            return 0;");
                }
                else
                {
                    tightBody.Append("            return r")
                        .Append(resultRegister.ToString(CultureInfo.InvariantCulture))
                        .AppendLine(";");
                }
            }

            var source = new StringBuilder(1536 + stateBody.Length + (tightBody?.Length ?? 0));
            source.AppendLine("// <auto-generated />");
            source.AppendLine("#nullable enable");
            source.AppendLine("using System;");
            source.AppendLine("using Ludots.Core.GraphRuntime;");
            source.AppendLine("using Ludots.Core.NodeLibraries.GASGraph;");
            source.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
            source.AppendLine();
            source.Append("public static class ").Append(GeneratedTypeName).AppendLine();
            source.AppendLine("{");
            source.Append("    public const string AssemblyMarker = \"")
                .Append(EscapeForCSharpString(assemblyMarker))
                .AppendLine("\";");
            source.AppendLine("    public const string EmitMode = \"specialize\";");
            if (symbols != null && symbols.Length > 0)
            {
                source.AppendLine("    private static readonly string[] Symbols = new string[]");
                source.AppendLine("    {");
                for (int i = 0; i < symbols.Length; i++)
                {
                    source.Append("        \"")
                        .Append(EscapeForCSharpString(symbols[i] ?? string.Empty))
                        .AppendLine("\",");
                }

                source.AppendLine("    };");
            }

            source.AppendLine("    private static readonly GraphInstruction[] Instructions = new GraphInstruction[]");
            source.AppendLine("    {");
            for (int i = 0; i < program.Length; i++)
            {
                AppendInstructionLiteral(source, program[i], indent: "        ");
                source.AppendLine(",");
            }

            source.AppendLine("    };");
            source.AppendLine();
            source.Append("    public static void ").Append(GeneratedMethodName)
                .AppendLine("(ref GraphExecutionState state)");
            source.AppendLine("    {");
            source.Append(stateBody);
            source.AppendLine("    }");
            if (tightBody != null)
            {
                source.AppendLine();
                source.Append("    public static int ").Append(GeneratedTightMethodName).AppendLine("()");
                source.AppendLine("    {");
                AppendTightLocals(source, usedInt, usedBool);
                source.Append(tightBody);
                source.AppendLine("    }");
            }

            source.AppendLine("}");
            return source.ToString();
        }

        private static void CollectSpecializeUses(
            GraphNodeOp op,
            in GraphInstruction ins,
            SortedSet<int> usedInt,
            SortedSet<int> usedBool,
            ref int resultRegister,
            ref bool sawIntWrite,
            ref bool needsText)
        {
            switch (op)
            {
                case GraphNodeOp.None:
                    break;
                case GraphNodeOp.ConstInt:
                    usedInt.Add(ins.Dst);
                    resultRegister = ins.Dst;
                    sawIntWrite = true;
                    break;
                case GraphNodeOp.AddInt:
                case GraphNodeOp.MoveInt:
                    usedInt.Add(ins.A);
                    if (op == GraphNodeOp.AddInt)
                    {
                        usedInt.Add(ins.B);
                    }

                    usedInt.Add(ins.Dst);
                    resultRegister = ins.Dst;
                    sawIntWrite = true;
                    break;
                case GraphNodeOp.CompareLtInt:
                case GraphNodeOp.CompareEqInt:
                    usedInt.Add(ins.A);
                    usedInt.Add(ins.B);
                    usedBool.Add(ins.Dst);
                    break;
                case GraphNodeOp.ConstBool:
                    usedBool.Add(ins.Dst);
                    break;
                case GraphNodeOp.JumpIfFalse:
                    usedBool.Add(ins.A);
                    break;
                case GraphNodeOp.HaltReturnInt:
                    usedInt.Add(ins.A);
                    break;
                case GraphNodeOp.ConstText:
                case GraphNodeOp.ConcatText:
                case GraphNodeOp.IntToText:
                case GraphNodeOp.FloatToText:
                case GraphNodeOp.SinkPresentationText:
                case GraphNodeOp.LoadTextKey:
                    needsText = true;
                    if (op == GraphNodeOp.IntToText)
                    {
                        usedInt.Add(ins.A);
                    }

                    break;
                case GraphNodeOp.Jump:
                case GraphNodeOp.ConstFloat:
                case GraphNodeOp.AddFloat:
                case GraphNodeOp.MulFloat:
                case GraphNodeOp.SubFloat:
                case GraphNodeOp.DivFloat:
                case GraphNodeOp.MinFloat:
                case GraphNodeOp.MaxFloat:
                case GraphNodeOp.ClampFloat:
                case GraphNodeOp.AbsFloat:
                case GraphNodeOp.NegFloat:
                case GraphNodeOp.CompareGtFloat:
                    break;
                default:
                    throw new InvalidOperationException(
                        $"Specialize emit does not implement op '{op}'. Use HandlerForward.");
            }
        }

        private static void AppendSpecializeInstruction(
            StringBuilder stateBody,
            StringBuilder? tightBody,
            int index,
            in GraphInstruction ins,
            int programLength)
        {
            GraphNodeOp op = (GraphNodeOp)ins.Op;
            switch (op)
            {
                case GraphNodeOp.None:
                    stateBody.AppendLine("            ;");
                    tightBody?.AppendLine("            ;");
                    break;
                case GraphNodeOp.ConstInt:
                    stateBody.Append("            state.I[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = ")
                        .Append(ins.Imm.ToString(CultureInfo.InvariantCulture))
                        .AppendLine(";");
                    tightBody?.Append("            r")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append(" = ")
                        .Append(ins.Imm.ToString(CultureInfo.InvariantCulture))
                        .AppendLine(";");
                    break;
                case GraphNodeOp.AddInt:
                    stateBody.Append("            state.I[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = state.I[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append("] + state.I[")
                        .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("];");
                    tightBody?.Append("            r")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append(" = r")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append(" + r")
                        .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                        .AppendLine(";");
                    break;
                case GraphNodeOp.MoveInt:
                    stateBody.Append("            state.I[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = state.I[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("];");
                    tightBody?.Append("            r")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append(" = r")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .AppendLine(";");
                    break;
                case GraphNodeOp.CompareLtInt:
                    AppendCompare(stateBody, tightBody, ins, "<");
                    break;
                case GraphNodeOp.CompareEqInt:
                    AppendCompare(stateBody, tightBody, ins, "==");
                    break;
                case GraphNodeOp.ConstBool:
                    stateBody.Append("            state.B[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = (byte)(")
                        .Append(ins.Imm != 0 ? "1" : "0")
                        .AppendLine(");");
                    tightBody?.Append("            b")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append(" = ")
                        .Append(ins.Imm != 0 ? "1" : "0")
                        .AppendLine(";");
                    break;
                case GraphNodeOp.ConstFloat:
                    stateBody.Append("            state.F[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = ")
                        .Append(FormatFloat(ins.ImmF))
                        .AppendLine("f;");
                    break;
                case GraphNodeOp.AddFloat:
                    AppendFloatBinary(stateBody, ins, "+");
                    break;
                case GraphNodeOp.MulFloat:
                    AppendFloatBinary(stateBody, ins, "*");
                    break;
                case GraphNodeOp.SubFloat:
                    AppendFloatBinary(stateBody, ins, "-");
                    break;
                case GraphNodeOp.DivFloat:
                    stateBody.Append("            state.F[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = state.F[")
                        .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                        .Append("] == 0f ? 0f : state.F[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append("] / state.F[")
                        .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("];");
                    break;
                case GraphNodeOp.MinFloat:
                    stateBody.Append("            state.F[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = MathF.Min(state.F[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append("], state.F[")
                        .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("]);");
                    break;
                case GraphNodeOp.MaxFloat:
                    stateBody.Append("            state.F[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = MathF.Max(state.F[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append("], state.F[")
                        .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("]);");
                    break;
                case GraphNodeOp.ClampFloat:
                    stateBody.Append("            state.F[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = Math.Clamp(state.F[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append("], state.F[")
                        .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                        .Append("], state.F[")
                        .Append(ins.C.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("]);");
                    break;
                case GraphNodeOp.AbsFloat:
                    stateBody.Append("            state.F[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = MathF.Abs(state.F[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("]);");
                    break;
                case GraphNodeOp.NegFloat:
                    stateBody.Append("            state.F[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = -state.F[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("];");
                    break;
                case GraphNodeOp.CompareGtFloat:
                    stateBody.Append("            state.B[")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append("] = (byte)(state.F[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append("] > state.F[")
                        .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("] ? 1 : 0);");
                    break;
                case GraphNodeOp.Jump:
                    AppendGoto(stateBody, ResolveJumpTarget(index, ins.Imm, programLength));
                    if (tightBody != null)
                    {
                        AppendGoto(tightBody, ResolveJumpTarget(index, ins.Imm, programLength));
                    }

                    break;
                case GraphNodeOp.JumpIfFalse:
                    int falseTarget = ResolveJumpTarget(index, ins.Imm, programLength);
                    stateBody.Append("            if (state.B[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append("] == 0) goto ")
                        .Append(LabelName(falseTarget))
                        .AppendLine(";");
                    tightBody?.Append("            if (b")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append(" == 0) goto ")
                        .Append(LabelName(falseTarget))
                        .AppendLine(";");
                    break;
                case GraphNodeOp.HaltReturnInt:
                    stateBody.Append("            state.ReturnInt = state.I[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("];");
                    stateBody.AppendLine("            state.Status = Ludots.Core.GraphRuntime.GraphExecutionStatus.Halted;");
                    stateBody.AppendLine("            return;");
                    tightBody?.Append("            return r")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .AppendLine(";");
                    break;
                case GraphNodeOp.ConstText:
                    stateBody.Append("            state.Text.Write(")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append(", Symbols[")
                        .Append(ins.Imm.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("].AsSpan());");
                    break;
                case GraphNodeOp.ConcatText:
                    stateBody.Append("            state.Text.Concat(")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append(", ")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .Append(", ")
                        .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                        .AppendLine(");");
                    break;
                case GraphNodeOp.IntToText:
                    stateBody.AppendLine("            {");
                    stateBody.Append("                Span<char> __buf = stackalloc char[")
                        .Append(GraphVmLimits.MaxTextCharsPerRegister.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("];");
                    stateBody.Append("                if (!state.I[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("].TryFormat(__buf, out int __written, provider: System.Globalization.CultureInfo.InvariantCulture))");
                    stateBody.AppendLine("                {");
                    stateBody.AppendLine("                    throw new InvalidOperationException(\"IntToText format overflow.\");");
                    stateBody.AppendLine("                }");
                    stateBody.Append("                state.Text.Write(")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .AppendLine(", __buf.Slice(0, __written));");
                    stateBody.AppendLine("            }");
                    break;
                case GraphNodeOp.FloatToText:
                    stateBody.AppendLine("            {");
                    stateBody.Append("                Span<char> __buf = stackalloc char[")
                        .Append(GraphVmLimits.MaxTextCharsPerRegister.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("];");
                    stateBody.Append("                if (!state.F[")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("].TryFormat(__buf, out int __written, format: \"0.###\", provider: System.Globalization.CultureInfo.InvariantCulture))");
                    stateBody.AppendLine("                {");
                    stateBody.AppendLine("                    throw new InvalidOperationException(\"FloatToText format overflow.\");");
                    stateBody.AppendLine("                }");
                    stateBody.Append("                state.Text.Write(")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .AppendLine(", __buf.Slice(0, __written));");
                    stateBody.AppendLine("            }");
                    break;
                case GraphNodeOp.SinkPresentationText:
                    stateBody.Append("            state.Api.PushPresentationText((GraphPresentationTextSurface)")
                        .Append(ins.Imm.ToString(CultureInfo.InvariantCulture))
                        .Append(", state.Text.Get(")
                        .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("));");
                    break;
                case GraphNodeOp.LoadTextKey:
                    stateBody.Append("            state.Text.Write(")
                        .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                        .Append(", state.Api.ResolvePresentationTextKey(")
                        .Append(ins.Imm.ToString(CultureInfo.InvariantCulture))
                        .AppendLine("));");
                    break;
                default:
                    throw new InvalidOperationException(
                        $"Specialize emit does not implement op '{op}' at instruction {index}.");
            }
        }

        private static void AppendFloatBinary(StringBuilder stateBody, in GraphInstruction ins, string token)
        {
            stateBody.Append("            state.F[")
                .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                .Append("] = state.F[")
                .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                .Append("] ")
                .Append(token)
                .Append(" state.F[")
                .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                .AppendLine("];");
        }

        private static void AppendCompare(
            StringBuilder stateBody,
            StringBuilder? tightBody,
            in GraphInstruction ins,
            string opToken)
        {
            stateBody.Append("            state.B[")
                .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                .Append("] = (byte)(state.I[")
                .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                .Append("] ")
                .Append(opToken)
                .Append(" state.I[")
                .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                .AppendLine("] ? 1 : 0);");
            tightBody?.Append("            b")
                .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                .Append(" = (byte)(r")
                .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                .Append(' ')
                .Append(opToken)
                .Append(" r")
                .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                .AppendLine(" ? 1 : 0);");
        }

        private static void AppendGoto(StringBuilder body, int targetIndex)
        {
            body.Append("            goto ")
                .Append(LabelName(targetIndex))
                .AppendLine(";");
        }

        private static void AppendTightLocals(
            StringBuilder source,
            SortedSet<int> usedInt,
            SortedSet<int> usedBool)
        {
            foreach (int r in usedInt)
            {
                source.Append("        int r")
                    .Append(r.ToString(CultureInfo.InvariantCulture))
                    .AppendLine(" = 0;");
            }

            foreach (int b in usedBool)
            {
                source.Append("        byte b")
                    .Append(b.ToString(CultureInfo.InvariantCulture))
                    .AppendLine(" = 0;");
            }
        }

        private static void AppendInstructionLiteral(StringBuilder sb, in GraphInstruction ins, string indent)
        {
            sb.Append(indent)
                .Append("new GraphInstruction { Op = ")
                .Append(ins.Op.ToString(CultureInfo.InvariantCulture))
                .Append(", Dst = ")
                .Append(ins.Dst.ToString(CultureInfo.InvariantCulture))
                .Append(", A = ")
                .Append(ins.A.ToString(CultureInfo.InvariantCulture))
                .Append(", B = ")
                .Append(ins.B.ToString(CultureInfo.InvariantCulture))
                .Append(", C = ")
                .Append(ins.C.ToString(CultureInfo.InvariantCulture))
                .Append(", Flags = ")
                .Append(ins.Flags.ToString(CultureInfo.InvariantCulture))
                .Append(", Imm = ")
                .Append(ins.Imm.ToString(CultureInfo.InvariantCulture))
                .Append(", ImmF = ")
                .Append(FormatFloat(ins.ImmF))
                .Append("f }");
        }

        /// <summary>
        /// VM advances PC before the handler, then Jump adds Imm. Target = index + 1 + Imm.
        /// Backward Imm is allowed (product loops / While lowering).
        /// </summary>
        private static int ResolveJumpTarget(int instructionIndex, int imm, int programLength)
        {
            long target = (long)instructionIndex + 1L + imm;
            if (target < 0)
            {
                throw new InvalidOperationException(
                    $"Jump/JumpIfFalse at index {instructionIndex} resolves to negative PC {target} (Imm={imm}).");
            }

            if (target > programLength)
            {
                return programLength;
            }

            return (int)target;
        }

        private static string LabelName(int index) =>
            "L" + index.ToString(CultureInfo.InvariantCulture);

        private static string FormatFloat(float value) =>
            value.ToString("G9", CultureInfo.InvariantCulture);

        private static string EscapeForCSharpString(string value) =>
            value
                .Replace("\\", "\\\\", StringComparison.Ordinal)
                .Replace("\"", "\\\"", StringComparison.Ordinal)
                .Replace("\n", "\\n", StringComparison.Ordinal)
                .Replace("\r", "\\r", StringComparison.Ordinal);
    }
}
