<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ludots.Core.csproj" />
    <ProjectReference Include="..\Ludots.Physics2D\Ludots.Physics2D.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Arch.System" />
  </ItemGroup>
</Project>
