<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ludots.Tools.FieldEditor</RootNamespace>
    <AssemblyName>field-editor</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\Ludots.Core.csproj" />
    <ProjectReference Include="..\..\src\Libraries\Raylib-cs\Raylib-cs.csproj" />
  </ItemGroup>
</Project>
