using System.Numerics;
using Arch.Core;

namespace Ludots.Core.Gameplay.Cue
{
    /// <summary>
    /// A pure data descriptor for a visual/audio cue event.
    /// This is generated by the GameplayCueSystem and consumed by the Presentation layer.
    /// </summary>
    public struct CueDescriptor
    {
        public int CueTagId;      // The Tag ID triggering this cue (e.g., Ability.Fireball)
        public Vector3 Position;  // World space position
        public Quaternion Rotation;
        public float Scale;
        
        public Entity Source;     // Optional source entity (for attachment)
        public Entity Target;     // Optional target entity (for attachment)
        
        // Future: AssetId for dynamic mesh loading
        public int AssetId;
    }
}
