namespace MassNavPlaygroundMod.UI;

internal readonly record struct MassNavPanelState(
    bool Visible,
    int TotalAgents,
    int ControllableAgents,
    int Blockers,
    int SelectedCount,
    uint SelectionRevision,
    float RenderFps,
    float RenderFrameMs,
    float PrimitiveRenderMs,
    int PrimitiveBufferCount,
    int PrimitiveInstances,
    int PrimitiveBatches,
    int VisibleEntities,
    float CameraTargetX,
    float CameraTargetY,
    float CameraDistanceCm,
    float FirstAgentX,
    float FirstAgentZ,
    int SelectionSnapshotsFrame,
    int StructuralChangesFrame,
    int FlowReconcileFrame)
{
    public static MassNavPanelState Empty => new(
        Visible: false,
        TotalAgents: 0,
        ControllableAgents: 0,
        Blockers: 0,
        SelectedCount: 0,
        SelectionRevision: 0,
        RenderFps: 0f,
        RenderFrameMs: 0f,
        PrimitiveRenderMs: 0f,
        PrimitiveBufferCount: 0,
        PrimitiveInstances: 0,
        PrimitiveBatches: 0,
        VisibleEntities: 0,
        CameraTargetX: 0f,
        CameraTargetY: 0f,
        CameraDistanceCm: 0f,
        FirstAgentX: 0f,
        FirstAgentZ: 0f,
        SelectionSnapshotsFrame: 0,
        StructuralChangesFrame: 0,
        FlowReconcileFrame: 0);
}
