namespace PerformerBlacksmithShowcaseMod.UI
{
    internal readonly record struct PerformerBlacksmithShowcasePanelState(
        float PanelLeft,
        float PanelTop,
        float PanelWidth,
        float PanelHeight,
        float ScrollHeight,
        string Title,
        string Subtitle,
        string ViewportLabel,
        string SceneSummary,
        string ScatterSummary,
        string LastChange,
        bool WorkingActive,
        bool NightActive,
        bool RootDestroyed,
        int RegionIndex,
        int DurabilityPreset,
        int ScatterTarget,
        int ScatterAppliedTotal,
        int ScatterMin,
        int ScatterMax,
        string BenchmarkSummary,
        string CapacitySummary,
        string[] ChecklistLines,
        string[] DiagnosticLines,
        string[] PerformerLines)
    {
        public static readonly PerformerBlacksmithShowcasePanelState Empty = new(
            PanelLeft: 12f,
            PanelTop: 12f,
            PanelWidth: 420f,
            PanelHeight: 640f,
            ScrollHeight: 520f,
            Title: "Performer Blacksmith Showcase",
            Subtitle: "Mouse-only control panel.",
            ViewportLabel: "1280 x 720",
            SceneSummary: "Waiting for showcase map.",
            ScatterSummary: "Scatter total 1",
            LastChange: string.Empty,
            WorkingActive: false,
            NightActive: false,
            RootDestroyed: false,
            RegionIndex: 0,
            DurabilityPreset: 0,
            ScatterTarget: 1,
            ScatterAppliedTotal: 1,
            ScatterMin: 1,
            ScatterMax: 2000,
            BenchmarkSummary: "Benchmark: unavailable",
            CapacitySummary: "Capacity: unavailable",
            ChecklistLines: new[] { "WAIT base tree: showcase map is not active." },
            DiagnosticLines: new[] { "Root entity: (missing)" },
            PerformerLines: new[] { "(no performer instances)" });
    }
}
