namespace CapabilityStandardStaticPresenter30kMod.UI
{
    internal readonly record struct CapabilityStandardStaticPresenter30kPanelState(
        float PanelLeft,
        float PanelTop,
        float PanelWidth,
        float PanelHeight,
        float ScrollHeight,
        string Title,
        string Subtitle,
        string ViewportLabel,
        string SceneSummary,
        string ScatterSummary,
        string LastChange,
        bool WorkingActive,
        bool NightActive,
        bool RootDestroyed,
        int RegionIndex,
        int DurabilityPreset,
        int ScatterTarget,
        int ScatterAppliedTotal,
        int ScatterMin,
        int ScatterMax,
        string BenchmarkSummary,
        string CapacitySummary,
        string[] ChecklistLines,
        string[] DiagnosticLines,
        string[] PresenterLines)
    {
        public static readonly CapabilityStandardStaticPresenter30kPanelState Empty = new(
            PanelLeft: 12f,
            PanelTop: 12f,
            PanelWidth: 420f,
            PanelHeight: 640f,
            ScrollHeight: 520f,
            Title: "Presenter CapabilityStaticPresenter Showcase",
            Subtitle: "Mouse-only control panel.",
            ViewportLabel: "1280 x 720",
            SceneSummary: "Waiting for showcase map.",
            ScatterSummary: "Scatter total 1",
            LastChange: string.Empty,
            WorkingActive: false,
            NightActive: false,
            RootDestroyed: false,
            RegionIndex: 0,
            DurabilityPreset: 0,
            ScatterTarget: 30000,
            ScatterAppliedTotal: 1,
            ScatterMin: 1,
            ScatterMax: 300000,
            BenchmarkSummary: "Benchmark: unavailable",
            CapacitySummary: "Capacity: unavailable",
            ChecklistLines: new[] { "WAIT base tree: showcase map is not active." },
            DiagnosticLines: new[] { "Root entity: (missing)" },
            PresenterLines: new[] { "(no presenter instances)" });
    }
}
