using System;
using System.Collections.Generic;
using Arch.Core;
using Ludots.Core.Association;
using Ludots.Core.Config;
using Ludots.Core.Diagnostics;
using Ludots.Core.Engine;
using Ludots.Core.Engine.Pacemaker;
using Ludots.Core.Engine.Physics2D;
using Ludots.Core.Engine.TimeFlow;
using Ludots.Core.EntityCollections;
using Ludots.Core.EntityQueries;
using Ludots.Core.Gameplay;
using Ludots.Core.Gameplay.AI.Config;
using Ludots.Core.Gameplay.Camera;
using Ludots.Core.Gameplay.Exchange;
using Ludots.Core.Gameplay.Narrative;
using Ludots.Core.Gameplay.Quests;
using Ludots.Core.Gameplay.GAS;
using Ludots.Core.Gameplay.GAS.Bindings;
using Ludots.Core.Gameplay.GAS.LiveSkillWorkbench;
using Ludots.Core.Gameplay.GAS.Input;
using Ludots.Core.Gameplay.GAS.Orders;
using Ludots.Core.Gameplay.GAS.Presentation;
using Ludots.Core.Gameplay.Items;
using Ludots.Core.Gameplay.Relationships;
using Ludots.Core.Gameplay.Relationships.Config;
using Ludots.Core.Gameplay.Spawning;
using Ludots.Core.Gameplay.Lifecycle;
using Ludots.Core.Gameplay.GAS.Systems;
using Ludots.Core.Gameplay.Progression;
using Ludots.Core.Gameplay.Teams;
using Ludots.Core.GraphRuntime;
using Ludots.Core.Hosting;
using Ludots.Core.Input.CommandSources;
using Ludots.Core.Input.Interaction;
using Ludots.Core.Input.Attributes;
using Ludots.Core.Input.Orders;
using Ludots.Core.Input.Runtime;
using Ludots.Core.Knowledge;
using Ludots.Core.ParticipantVisibility;
using Ludots.Core.Map;
using Ludots.Core.Map.Board;
using Ludots.Core.Map.Hex;
using Ludots.Core.Modding;
using Ludots.Core.Movement;
using Ludots.Core.Navigation.GraphCore;
using Ludots.Core.Navigation.GraphWorld;
using Ludots.Core.Navigation.AgentProfiles;
using Ludots.Core.Navigation.NavMesh;
using Ludots.Core.Navigation.NavMesh.Bake;
using Ludots.Core.Navigation.NavMesh.Config;
using Ludots.Core.Navigation.Pathing;
using Ludots.Core.Navigation.Pathing.Config;
using Ludots.Core.Navigation.Terrain;
using Ludots.Core.NodeLibraries.GASGraph;
using Ludots.Core.NodeLibraries.GASGraph.Host;
using Ludots.Core.Persistence;
using Ludots.Core.Presentation;
using Ludots.Core.Presentation.Assets;
using Ludots.Core.Presentation.Camera;
using Ludots.Core.Presentation.ChunkDebug;
using Ludots.Core.Presentation.Commands;
using Ludots.Core.Presentation.Config;
using Ludots.Core.Presentation.Events;
using Ludots.Core.Presentation.Hud;
using Ludots.Core.Presentation.Instancing;
using Ludots.Core.Presentation.Minimap;
using Ludots.Core.Presentation.Presenters;
using Ludots.Core.Presentation.Particles;
using Ludots.Core.Presentation.Requests;
using Ludots.Platform.Abstractions;
using Ludots.Core.Presentation.Rendering;
using Ludots.Core.Presentation.Surfaces;
using Ludots.Core.Presentation.Systems;
using Ludots.Core.Presentation.Terrain;
using Ludots.Core.Registry;
using Ludots.Core.Spatial;
using Ludots.Core.StructureCollision;
using Ludots.Core.Systems;
using Ludots.Core.UI;
using Ludots.Core.UI.CommandDeck;
using Ludots.Core.UI.EntityCommandPanels;
using Ludots.Core.UI.ProductionOverview;
using Ludots.Core.Vision;
using Ludots.Platform.Abstractions;

namespace Ludots.Core.Scripting
{
    /// <summary>
    /// Compile-time typed keys for Core engine services.
    /// Mod-specific keys should be defined inside each mod project, not here.
    /// </summary>
    public static class CoreServiceKeys
    {
        // --- ECS & Engine ---
        public static readonly ServiceKey<World> World = new("World");
        public static readonly ServiceKey<WorldMap> WorldMap = new("WorldMap");
        public static readonly ServiceKey<VertexMap> VertexMap = new("VertexMap");
        public static readonly ServiceKey<GameSession> GameSession = new("GameSession");
        public static readonly ServiceKey<GameEngine> Engine = new("Engine");
        public static readonly ServiceKey<ISystemRegistrar> SystemRegistrar = new("SystemRegistrar");
        public static readonly ServiceKey<ModRegistrySet> ModRegistrySet = new("ModRegistrySet");
        public static readonly ServiceKey<GameConfig> GameConfig = new("GameConfig");
        public static readonly ServiceKey<int> HostFrameIndex = new("HostFrameIndex");
        public static readonly ServiceKey<SystemFactoryRegistry> SystemFactoryRegistry = new("SystemFactoryRegistry");
        public static readonly ServiceKey<TimeFlowService> TimeFlow = new("TimeFlow");
        public static readonly ServiceKey<TriggerDecoratorRegistry> TriggerDecoratorRegistry = new("TriggerDecoratorRegistry");
        public static readonly ServiceKey<SaveParticipantRegistry> SaveParticipants = new("SaveParticipants");
        public static readonly ServiceKey<PoseAuthorityArbiter> PoseAuthorityArbiter = new("PoseAuthorityArbiter");

        // --- Map ---
        public static readonly ServiceKey<MapId> MapId = new("MapId");
        public static readonly ServiceKey<List<string>> MapTags = new("MapTags");
        public static readonly ServiceKey<MapFeatureFlags> MapFeatureFlags = new("MapFeatureFlags");
        public static readonly ServiceKey<MapLoadStatus> MapLoadStatus = new("MapLoadStatus");
        public static readonly ServiceKey<MapSession> MapSession = new("MapSession");
        public static readonly ServiceKey<MapSessionManager> MapSessions = new("MapSessions");
        public static readonly ServiceKey<IMapLoadCompletionGate> MapLoadCompletionGate = new("MapLoadCompletionGate");
        public static readonly ServiceKey<IFocusedMapLoadStateSink> FocusedMapLoadStateSink = new("FocusedMapLoadStateSink");
        public static readonly ServiceKey<BoardIdRegistry> BoardIdRegistry = new("BoardIdRegistry");
        public static readonly ServiceKey<MapContext> MapContext = new("MapContext");
        public static readonly ServiceKey<MapLaunchContext> MapLaunchContext = new("MapLaunchContext");

        // --- UI ---
        public static readonly ServiceKey<IUiSystem> UISystem = new("UISystem");
        public static readonly ServiceKey<object> UIRoot = new("UIRoot");
        public static readonly ServiceKey<object> UiSurfaceHost = new("UiSurfaceHost");
        public static readonly ServiceKey<bool> UiCaptured = new("UiCaptured");
        public static readonly ServiceKey<bool> UiWheelCaptured = new("UiWheelCaptured");
        public static readonly ServiceKey<IEntityCommandPanelService> EntityCommandPanelService = new("EntityCommandPanelService");
        public static readonly ServiceKey<IEntityCommandPanelHandleStore> EntityCommandPanelHandleStore = new("EntityCommandPanelHandleStore");
        public static readonly ServiceKey<IEntityCommandPanelSourceRegistry> EntityCommandPanelSourceRegistry = new("EntityCommandPanelSourceRegistry");
        public static readonly ServiceKey<IEntityCommandPanelToolbarProvider> EntityCommandPanelToolbarProvider = new("EntityCommandPanelToolbarProvider");
        public static readonly ServiceKey<object> UiTextMeasurer = new("UiTextMeasurer");
        public static readonly ServiceKey<object> UiImageSizeProvider = new("UiImageSizeProvider");
        public static readonly ServiceKey<Ludots.Core.UI.PanelHosting.PanelHost> PanelHost = new("PanelHost");
        public static readonly ServiceKey<Ludots.Core.UI.PanelHosting.PanelTemplateRegistry> PanelTemplateRegistry = new("PanelTemplateRegistry");
        public static readonly ServiceKey<Ludots.Core.UI.PanelActivation.PanelActivationApi> PanelActivationApi = new("PanelActivationApi");
        public static readonly ServiceKey<Ludots.Core.UI.PanelActivation.UiPanelActivationStore> PanelActivationStore = new("PanelActivationStore");

        // --- Input ---
        public static readonly ServiceKey<PlayerInputHandler> InputHandler = new("InputHandler");
        public static readonly ServiceKey<IInputActionReader> AuthoritativeInput = new("AuthoritativeInput");
        public static readonly ServiceKey<AuthoritativePointerButtonSnapshot> AuthoritativePointerButtons = new("AuthoritativePointerButtons");
        public static readonly ServiceKey<AuthoritativeGroundPointerOverride> AuthoritativeGroundPointerOverride = new("AuthoritativeGroundPointerOverride");
        public static readonly ServiceKey<IInputBackend> InputBackend = new("InputBackend");
        public static readonly ServiceKey<SyntheticInputDevice> SyntheticInput = new("SyntheticInput");
        public static readonly ServiceKey<IHostFrameCapture> HostFrameCapture = new("HostFrameCapture");
        public static readonly ServiceKey<List<IInputFrameConsumer>> InputFrameConsumers = new("InputFrameConsumers");
        public static readonly ServiceKey<bool> PointerInputCaptured = new("PointerInputCaptured");
        public static readonly ServiceKey<InputActionAttributeBindingRegistry> InputActionAttributeBindingRegistry = new("InputActionAttributeBindingRegistry");

        // --- Camera & View ---
        public static readonly ServiceKey<IViewController> ViewController = new("ViewController");
        public static readonly ServiceKey<IScreenProjector> ScreenProjector = new("ScreenProjector");
        public static readonly ServiceKey<IScreenRayProvider> ScreenRayProvider = new("ScreenRayProvider");
        public static readonly ServiceKey<CameraCullingFocusOverride> CameraCullingFocusOverride = new("CameraCullingFocusOverride");
        public static readonly ServiceKey<IVisualGroundProjector> VisualGroundProjector = new("VisualGroundProjector");
        public static readonly ServiceKey<IVisualHeightmap> VisualHeightmap = new("VisualHeightmap");
        public static readonly ServiceKey<StructureCollisionAsset> StructureCollisionAsset = new("StructureCollisionAsset");
        public static readonly ServiceKey<StructureCollisionRuntimeState> StructureCollisionRuntimeState = new("StructureCollisionRuntimeState");
        public static readonly ServiceKey<IGroundSurfaceSampler> GroundSurfaceSampler = new("GroundSurfaceSampler");
        public static readonly ServiceKey<CameraPoseRequest> CameraPoseRequest = new("CameraPoseRequest");
        public static readonly ServiceKey<VirtualCameraRequest> VirtualCameraRequest = new("VirtualCameraRequest");
        public static readonly ServiceKey<VirtualCameraRegistry> VirtualCameraRegistry = new("VirtualCameraRegistry");
        public static readonly ServiceKey<CameraBehaviorInputState> CameraBehaviorInputState = new("CameraBehaviorInputState");
        public static readonly ServiceKey<CameraImpulseRuntime> CameraImpulseRuntime = new("CameraImpulseRuntime");
        public static readonly ServiceKey<PlatformManagedCameraDriverRegistry> PlatformManagedCameraDriverRegistry = new("PlatformManagedCameraDriverRegistry");
        public static readonly ServiceKey<IPlatformManagedCameraHostService> PlatformManagedCameraHostService = new("PlatformManagedCameraHostService");
        public static readonly ServiceKey<QuestDefinitionRegistry> QuestDefinitionRegistry = new("QuestDefinitionRegistry");
        public static readonly ServiceKey<QuestRuntimeService> QuestRuntimeService = new("QuestRuntimeService");
        public static readonly ServiceKey<NarrativeDefinitionRegistry> NarrativeDefinitions = new("NarrativeDefinitions");
        public static readonly ServiceKey<NarrativeDirector> NarrativeDirector = new("NarrativeDirector");

        // --- GAS Core ---
        public static readonly ServiceKey<IClock> Clock = new("Clock");
        public static readonly ServiceKey<GasClockStepPolicy> GasClockStepPolicy = new("GasClockStepPolicy");
        public static readonly ServiceKey<GasClocks> GasClocks = new("GasClocks");
        public static readonly ServiceKey<GasBudget> GasBudget = new("GasBudget");
        public static readonly ServiceKey<GasDiagnosticEventBuffer> GasDiagnosticEventBuffer = new("GasDiagnosticEventBuffer");
        public static readonly ServiceKey<GasController> GasController = new("GasController");
        public static readonly ServiceKey<GasConditionRegistry> GasConditionRegistry = new("GasConditionRegistry");
        public static readonly ServiceKey<TagOps> TagOps = new("TagOps");
        public static readonly ServiceKey<DirtyEntityQueue> DirtyEntityQueue = new("DirtyEntityQueue");
        public static readonly ServiceKey<EffectTemplateRegistry> EffectTemplateRegistry = new("EffectTemplateRegistry");
        public static readonly ServiceKey<TargetDispatchPresetRegistry> TargetDispatchPresetRegistry = new("TargetDispatchPresetRegistry");
        public static readonly ServiceKey<EffectRequestQueue> EffectRequestQueue = new("EffectRequestQueue");
        public static readonly ServiceKey<OrderAdmissionResultBuffer> OrderAdmissionResultBuffer = new("OrderAdmissionResultBuffer");
        public static readonly ServiceKey<OrderTerminalResultBuffer> OrderTerminalResultBuffer = new("OrderTerminalResultBuffer");
        public static readonly ServiceKey<AbilityDefinitionRegistry> AbilityDefinitionRegistry = new("AbilityDefinitionRegistry");
        public static readonly ServiceKey<AbilityFormSetRegistry> AbilityFormSetRegistry = new("AbilityFormSetRegistry");
        public static readonly ServiceKey<ProgressionDefinitionRegistry> ProgressionDefinitionRegistry = new("ProgressionDefinitionRegistry");
        public static readonly ServiceKey<ProgressionRequirementRegistry> ProgressionRequirementRegistry = new("ProgressionRequirementRegistry");
        public static readonly ServiceKey<ScopeKeyRegistry> ScopeKeyRegistry = new("ScopeKeyRegistry");
        public static readonly ServiceKey<ScopeResolver> ScopeResolver = new("ScopeResolver");
        public static readonly ServiceKey<ProgressionRequirementEvaluator> ProgressionRequirementEvaluator = new("ProgressionRequirementEvaluator");
        public static readonly ServiceKey<ContextGroupRegistry> ContextGroupRegistry = new("ContextGroupRegistry");
        public static readonly ServiceKey<GraphProgramRegistry> GraphProgramRegistry = new("GraphProgramRegistry");
        public static readonly ServiceKey<GraphFunctionCatalog> GraphFunctionCatalog = new("GraphFunctionCatalog");
        public static readonly ServiceKey<GraphActionCatalog> GraphActionCatalog = new("GraphActionCatalog");
        public static readonly ServiceKey<GraphLookupTableRegistry> GraphLookupTableRegistry = new("GraphLookupTableRegistry");
        public static readonly ServiceKey<LiveGasEditPipeline> LiveGasEditPipeline = new("LiveGasEditPipeline");
        public static readonly ServiceKey<LiveAttributeCommandExecutor> LiveAttributeCommandExecutor = new("LiveAttributeCommandExecutor");
        public static readonly ServiceKey<LiveEffectChainTracer> LiveEffectChainTracer = new("LiveEffectChainTracer");
        public static readonly ServiceKey<IAiSkillDraftGenerator> AiSkillDraftGenerator = new("AiSkillDraftGenerator");
        public static readonly ServiceKey<LiveAiDraftBinder> LiveAiDraftBinder = new("LiveAiDraftBinder");
        public static readonly ServiceKey<LiveEditModSaveService> LiveEditModSaveService = new("LiveEditModSaveService");
        public static readonly ServiceKey<GasGraphRuntimeProductionServices> GasGraphRuntimeProductionServices = new("GasGraphRuntimeProductionServices");
        public static readonly ServiceKey<GasGraphRuntimeApi> GasGraphRuntimeApi = new("GasGraphRuntimeApi");
        public static readonly ServiceKey<GasGraphOpHandlerTable> GasGraphOpHandlerTable = new("GasGraphOpHandlerTable");
        public static readonly ServiceKey<GraphOutputSchemaRegistry> GraphOutputSchemaRegistry = new("GraphOutputSchemaRegistry");
        public static readonly ServiceKey<StringIntRegistry> GraphOutputValueKeyRegistry = new("GraphOutputValueKeyRegistry");
        public static readonly ServiceKey<GraphOutputValueStore> GraphOutputValueStore = new("GraphOutputValueStore");
        public static readonly ServiceKey<GraphReturnWriter> GraphReturnWriter = new("GraphReturnWriter");
        public static readonly ServiceKey<ExtensionAttributeRegistry> ExtensionAttributeRegistry = new("ExtensionAttributeRegistry");
        public static readonly ServiceKey<AttributeSchemaUpdateQueue> AttributeSchemaUpdateQueue = new("AttributeSchemaUpdateQueue");
        public static readonly ServiceKey<DeferredTriggerQueue> DeferredTriggerQueue = new("DeferredTriggerQueue");
        public static readonly ServiceKey<AttributeSinkRegistry> AttributeSinkRegistry = new("AttributeSinkRegistry");
        public static readonly ServiceKey<AttributeBindingRegistry> AttributeBindingRegistry = new("AttributeBindingRegistry");
        public static readonly ServiceKey<ItemShapeRegistry> ItemShapeRegistry = new("ItemShapeRegistry");
        public static readonly ServiceKey<ItemLayoutRegistry> ItemLayoutRegistry = new("ItemLayoutRegistry");
        public static readonly ServiceKey<ItemDefinitionRegistry> ItemDefinitionRegistry = new("ItemDefinitionRegistry");
        public static readonly ServiceKey<OwnershipResolver> OwnershipResolver = new("OwnershipResolver");
        public static readonly ServiceKey<InventoryRuntimeService> InventoryRuntimeService = new("InventoryRuntimeService");
        public static readonly ServiceKey<ExchangeOperationRegistry> ExchangeOperationRegistry = new("ExchangeOperationRegistry");
        public static readonly ServiceKey<ExchangeScopedOperationStore> ExchangeScopedOperationStore = new("ExchangeScopedOperationStore");
        public static readonly ServiceKey<ExchangeRuntime> ExchangeRuntime = new("ExchangeRuntime");
        public static readonly ServiceKey<RelationshipTypeRegistry> RelationshipTypeRegistry = new("RelationshipTypeRegistry");
        public static readonly ServiceKey<RelationshipMetricRegistry> RelationshipMetricRegistry = new("RelationshipMetricRegistry");
        public static readonly ServiceKey<RelationshipFlagRegistry> RelationshipFlagRegistry = new("RelationshipFlagRegistry");
        public static readonly ServiceKey<RelationshipBandRegistry> RelationshipBandRegistry = new("RelationshipBandRegistry");
        public static readonly ServiceKey<RelationshipReasonRegistry> RelationshipReasonRegistry = new("RelationshipReasonRegistry");
        public static readonly ServiceKey<RelationshipChangeBuffer> RelationshipChangeBuffer = new("RelationshipChangeBuffer");
        public static readonly ServiceKey<RelationshipRuntime> RelationshipRuntime = new("RelationshipRuntime");
        public static readonly ServiceKey<RelationshipCatalogConfig> RelationshipCatalogConfig = new("RelationshipCatalogConfig");
        public static readonly ServiceKey<RelationshipCatalogRuntime> RelationshipCatalogRuntime = new("RelationshipCatalogRuntime");
        public static readonly ServiceKey<ControlDomainQuery> ControlDomainQuery = new("ControlDomainQuery");
        public static readonly ServiceKey<DomainStanceQuery> DomainStanceQuery = new("DomainStanceQuery");
        public static readonly ServiceKey<AssociationControlProfileRuntime> AssociationControlProfileRuntime = new("AssociationControlProfileRuntime");
        public static readonly ServiceKey<TeamEntityLookup> TeamEntityLookup = new("TeamEntityLookup");
        public static readonly ServiceKey<PlayerEntityLookup> PlayerEntityLookup = new("PlayerEntityLookup");
        public static readonly ServiceKey<EntitySetQueryRuntime> EntitySetQueryRuntime = new("EntitySetQueryRuntime");
        public static readonly ServiceKey<KnowledgeProjectionStore> KnowledgeProjectionStore = new("KnowledgeProjectionStore");
        public static readonly ServiceKey<KnowledgeRelationCollectionProjector> KnowledgeRelationCollectionProjector = new("KnowledgeRelationCollectionProjector");
        public static readonly ServiceKey<KnowledgeProjectionResolver> KnowledgeProjectionResolver = new("KnowledgeProjectionResolver");
        public static readonly ServiceKey<DynamicParticipantVisibilityPublisher> DynamicParticipantVisibilityPublisher = new("DynamicParticipantVisibilityPublisher");
        public static readonly ServiceKey<FogLayerRegistry> VisionFogLayerRegistry = new("Vision.FogLayerRegistry");
        public static readonly ServiceKey<FogFieldStore> VisionFogFieldStore = new("Vision.FogFieldStore");
        public static readonly ServiceKey<FogSnapshotStore> VisionFogSnapshotStore = new("Vision.FogSnapshotStore");
        public static readonly ServiceKey<FogCellMap> VisionFogCellMap = new("Vision.FogCellMap");
        public static readonly ServiceKey<VisionResolver> VisionResolver = new("Vision.Resolver");
        public static readonly ServiceKey<FogKnowledgeProjector> FogKnowledgeProjector = new("Vision.FogKnowledgeProjector");
        public static readonly ServiceKey<KnowledgeAreaRevealRuntime> KnowledgeAreaRevealRuntime = new("Vision.KnowledgeAreaRevealRuntime");
        public static readonly ServiceKey<Entity> RelationshipEventSource = new("RelationshipEvent.Source");
        public static readonly ServiceKey<Entity> RelationshipEventTarget = new("RelationshipEvent.Target");
        public static readonly ServiceKey<Entity> RelationshipEventTeam = new("RelationshipEvent.Team");
        public static readonly ServiceKey<int> RelationshipEventMetricId = new("RelationshipEvent.MetricId");
        public static readonly ServiceKey<int> RelationshipEventMetricValue = new("RelationshipEvent.MetricValue");
        public static readonly ServiceKey<int> RelationshipEventTypeId = new("RelationshipEvent.TypeId");
        public static readonly ServiceKey<int> RelationshipEventReasonId = new("RelationshipEvent.ReasonId");
        public static readonly ServiceKey<int> RelationshipEventCount = new("RelationshipEvent.Count");

        // --- GAS Input / Command Sources / Orders ---
        public static readonly ServiceKey<InputRequestQueue> InputRequestQueue = new("InputRequestQueue");
        public static readonly ServiceKey<InputRequestQueue> AbilityInputRequestQueue = new("AbilityInputRequestQueue");
        public static readonly ServiceKey<InputResponseBuffer> InputResponseBuffer = new("InputResponseBuffer");
        public static readonly ServiceKey<RuntimeEntitySpawnQueue> RuntimeEntitySpawnQueue = new("RuntimeEntitySpawnQueue");
        public static readonly ServiceKey<RuntimeEntityLifecycleQueue> RuntimeEntityLifecycleQueue = new("RuntimeEntityLifecycleQueue");
        public static readonly ServiceKey<RuntimeEntityLifecycleReceiptQueue> RuntimeEntityLifecycleReceiptQueue = new("RuntimeEntityLifecycleReceiptQueue");
        public static readonly ServiceKey<RuntimeEntitySpawnReceiptChannelRegistry> RuntimeEntitySpawnReceiptChannelRegistry = new("RuntimeEntitySpawnReceiptChannelRegistry");
        public static readonly ServiceKey<EntityTemplateKeyRegistry> EntityTemplateKeyRegistry = new("EntityTemplateKeyRegistry");
        public static readonly ServiceKey<CommandSourceAcquisitionConfig> CommandSourceAcquisitionConfig = new("CommandSourceAcquisitionConfig");
        public static readonly ServiceKey<EntityCollectionStore> EntityCollectionStore = new("EntityCollectionStore");
        public static readonly ServiceKey<StringIntRegistry> EntityCollectionKeyRegistry = new("EntityCollectionKeyRegistry");
        public static readonly ServiceKey<DomainRoutedCollectionWriter> DomainRoutedCollectionWriter = new("DomainRoutedCollectionWriter");
        public static readonly ServiceKey<ControlPlaneView> ControlPlaneView = new("ControlPlaneView");
        public static readonly ServiceKey<InteractionActionBindings> InteractionActionBindings = new("InteractionActionBindings");
        public static readonly ServiceKey<InteractionContextStack> InteractionContextStack = new("InteractionContextStack");
        public static readonly ServiceKey<FilterProfileRegistry> FilterProfileRegistry = new("FilterProfileRegistry");
        public static readonly ServiceKey<CommandIntentProfileRegistry> CommandIntentProfileRegistry = new("CommandIntentProfileRegistry");
        public static readonly ServiceKey<CastDispatchProfileRegistry> CastDispatchProfileRegistry = new("CastDispatchProfileRegistry");
        public static readonly ServiceKey<InteractionContextProfileRegistry> InteractionContextProfileRegistry = new("InteractionContextProfileRegistry");
        public static readonly ServiceKey<CastCommitProfileRegistry> CastCommitProfileRegistry = new("CastCommitProfileRegistry");
        public static readonly ServiceKey<ClientCastPreferenceStore> ClientCastPreferenceStore = new("ClientCastPreferenceStore");
        public static readonly ServiceKey<ControlSchemeRuntime> ControlSchemeRuntime = new("ControlSchemeRuntime");
        public static readonly ServiceKey<Ludots.Core.UI.EntityCommandPanels.AbilityAggregationProfileRegistry> AbilityAggregationProfileRegistry = new("AbilityAggregationProfileRegistry");
        public static readonly ServiceKey<Ludots.Core.UI.CommandDeck.CommandDeckProfileRegistry> CommandDeckProfileRegistry = new("CommandDeckProfileRegistry");
        public static readonly ServiceKey<Ludots.Core.UI.CommandDeck.CommandDeckRouteResolver> CommandDeckRouteResolver = new("CommandDeckRouteResolver");
        public static readonly ServiceKey<Ludots.Core.UI.ProductionOverview.ProductionOverviewProfileRegistry> ProductionOverviewProfileRegistry = new("ProductionOverviewProfileRegistry");
        public static readonly ServiceKey<ContextBoundCollectionWriter> ContextBoundCollectionWriter = new("ContextBoundCollectionWriter");
        public static readonly ServiceKey<RuntimeEntitySpawnReceiptQueue> RuntimeEntitySpawnReceiptQueue = new("RuntimeEntitySpawnReceiptQueue");
        public static readonly ServiceKey<InputOrderMappingSystem> ActiveInputOrderMapping = new("ActiveInputOrderMapping");
        public static readonly ServiceKey<OrderQueue> OrderQueue = new("OrderQueue");
        public static readonly ServiceKey<OrderTypeRegistry> OrderTypeRegistry = new("OrderTypeRegistry");
        public static readonly ServiceKey<OrderRuleRegistry> OrderRuleRegistry = new("OrderRuleRegistry");
        public static readonly ServiceKey<OrderBufferSystem> OrderBufferSystem = new("OrderBufferSystem");
        public static readonly ServiceKey<OrderRequestQueue> OrderRequestQueue = new("OrderRequestQueue");
        public static readonly ServiceKey<ResponseChainTelemetryBuffer> ResponseChainTelemetryBuffer = new("ResponseChainTelemetryBuffer");
        public static readonly ServiceKey<OrderQueue> ChainOrderQueue = new("ChainOrderQueue");
        public static readonly ServiceKey<ResponseChainUiState> ResponseChainUiState = new("ResponseChainUiState");
        public static readonly ServiceKey<IEntityCommandPanelCollectionQueryConfigRegistry> EntityCommandPanelCollectionQueryConfigRegistry =
            new("EntityCommandPanelCollectionQueryConfigRegistry");

        // --- Simulation ---
        public static readonly ServiceKey<SimulationLoopController> SimulationLoopController = new("SimulationLoopController");
        public static readonly ServiceKey<Physics2DTickPolicy> Physics2DTickPolicy = new("Physics2DTickPolicy");
        public static readonly ServiceKey<Physics2DSolverConfig> Physics2DSolverConfig = new("Physics2DSolverConfig");
        public static readonly ServiceKey<Physics2DBroadphasePolicy> Physics2DBroadphasePolicy = new("Physics2DBroadphasePolicy");
        public static readonly ServiceKey<object> Physics2DShapeStorage = new("Physics2D.ShapeStorage");
        public static readonly ServiceKey<Physics2DController> Physics2DController = new("Physics2DController");
        public static readonly ServiceKey<Physics2DKinematicConfig> Physics2DKinematicConfig = new("Physics2DKinematicConfig");
        public static readonly ServiceKey<Ludots.Core.Physics2D.KinematicTargetPoseBuffer2D> Physics2DKinematicPoseBuffer = new("Physics2D.KinematicPoseBuffer");
        public static readonly ServiceKey<Ludots.Core.Physics2D.ContactEventQueue2D> Physics2DContactEvents = new("Physics2D.ContactEvents");

        // --- Presentation ---
        public static readonly ServiceKey<PresentationEventStream> PresentationEventStream = new("PresentationEventStream");
        public static readonly ServiceKey<PresentationOwnerChangeBuffer> PresentationOwnerChangeBuffer = new("PresentationOwnerChangeBuffer");
        public static readonly ServiceKey<PresenterCommandBuffer> PresenterCommandBuffer = new("PresenterCommandBuffer");
        public static readonly ServiceKey<MeshAssetRegistry> PresentationMeshAssetRegistry = new("PresentationMeshAssetRegistry");
        public static readonly ServiceKey<ParticleVfxRegistry> PresentationParticleVfxRegistry = new("PresentationParticleVfxRegistry");
        public static readonly ServiceKey<PresentationMaterialRegistry> PresentationMaterialRegistry = new("PresentationMaterialRegistry");
        public static readonly ServiceKey<PresentationLodProfileRegistry> PresentationLodProfileRegistry = new("PresentationLodProfileRegistry");
        public static readonly ServiceKey<InstancedBatchAssetRegistry> InstancedBatchAssetRegistry = new("InstancedBatchAssetRegistry");
        public static readonly ServiceKey<InstancedBatchRequestBuffer> InstancedBatchRequestBuffer = new("InstancedBatchRequestBuffer");
        public static readonly ServiceKey<InstancedBatchOperationBuffer> InstancedBatchOperationBuffer = new("InstancedBatchOperationBuffer");
        public static readonly ServiceKey<AnimatorControllerRegistry> AnimatorControllerRegistry = new("AnimatorControllerRegistry");
        public static readonly ServiceKey<AnimationClipRegistry> AnimationClipRegistry = new("AnimationClipRegistry");
        public static readonly ServiceKey<AnimationProfileRegistry> AnimationProfileRegistry = new("AnimationProfileRegistry");
        public static readonly ServiceKey<PresentationStableIdAllocator> PresentationStableIdAllocator = new("PresentationStableIdAllocator");
        public static readonly ServiceKey<PresenterVisualStableIdTable> PresenterVisualStableIdTable = new("PresenterVisualStableIdTable");
        public static readonly ServiceKey<StableDrawCache> PresentationStableDrawCache = new("PresentationStableDrawCache");
        public static readonly ServiceKey<PresentationTargetGeneration> PresentationTargetGeneration = new("PresentationTargetGeneration");
        public static readonly ServiceKey<PrimitiveDrawBuffer> PresentationPrimitiveDrawBuffer = new("PresentationPrimitiveDrawBuffer");
        public static readonly ServiceKey<PrimitiveDrawBuffer> PresentationVisualSnapshotBuffer = new("PresentationVisualSnapshotBuffer");
        public static readonly ServiceKey<PresentationVisualProxyBuffer> PresentationVisualProxyBuffer = new("PresentationVisualProxyBuffer");
        public static readonly ServiceKey<PresentationVisualRequestBuffer> PresentationVisualRequestBuffer = new("PresentationVisualRequestBuffer");
        public static readonly ServiceKey<PresentationAdapterCapabilities> PresentationAdapterCapabilities = new("PresentationAdapterCapabilities");
        public static readonly ServiceKey<SkinnedVisualBatchBuffer> PresentationSkinnedVisualBatchBuffer = new("PresentationSkinnedVisualBatchBuffer");
        public static readonly ServiceKey<PresentationRequestBuffer> PresentationRequestBuffer = new("PresentationRequestBuffer");
        public static readonly ServiceKey<GlobalFieldVisualBuffer> GlobalFieldVisualBuffer = new("GlobalFieldVisualBuffer");
        public static readonly ServiceKey<WorldHudBatchBuffer> PresentationWorldHudBuffer = new("PresentationWorldHudBuffer");
        public static readonly ServiceKey<WorldHudStringTable> PresentationWorldHudStrings = new("PresentationWorldHudStrings");
        public static readonly ServiceKey<PresentationTextCatalog> PresentationTextCatalog = new("PresentationTextCatalog");
        public static readonly ServiceKey<PresentationTextLocaleSelection> PresentationTextLocaleSelection = new("PresentationTextLocaleSelection");
        public static readonly ServiceKey<ScreenHudBatchBuffer> PresentationScreenHudBuffer = new("PresentationScreenHudBuffer");
        public static readonly ServiceKey<ScreenOverlayBuffer> ScreenOverlayBuffer = new("ScreenOverlayBuffer");
        public static readonly ServiceKey<MinimapRuntime> MinimapRuntime = new("MinimapRuntime");
        public static readonly ServiceKey<MinimapFocusCollectionProvider> MinimapFocusCollectionProvider = new("MinimapFocusCollectionProvider");
        public static readonly ServiceKey<MinimapKnowledgeViewerProvider> MinimapKnowledgeViewerProvider = new("MinimapKnowledgeViewerProvider");
        public static readonly ServiceKey<MinimapMarkerBuffer> MinimapMarkerBuffer = new("MinimapMarkerBuffer");
        public static readonly ServiceKey<MinimapScreenMarkerBuffer> MinimapScreenMarkerBuffer = new("MinimapScreenMarkerBuffer");
        public static readonly ServiceKey<ChunkDebugPanelRuntime> ChunkDebugPanelRuntime = new("ChunkDebugPanelRuntime");
        public static readonly ServiceKey<RenderDebugState> RenderDebugState = new("RenderDebugState");
        public static readonly ServiceKey<bool> PresentationAudienceRevealHidden = new("PresentationAudienceRevealHidden");
        public static readonly ServiceKey<RenderCameraDebugState> RenderCameraDebugState = new("RenderCameraDebugState");
        public static readonly ServiceKey<CameraCullingDebugState> CameraCullingDebugState = new("CameraCullingDebugState");
        public static readonly ServiceKey<PresentationTimingDiagnostics> PresentationTimingDiagnostics = new("PresentationTimingDiagnostics");
        public static readonly ServiceKey<PresentationFrameSetupSystem> PresentationFrameSetup = new("PresentationFrameSetup");
        public static readonly ServiceKey<IBenchmarkSceneController> BenchmarkSceneController = new("BenchmarkSceneController");
        public static readonly ServiceKey<TransientMarkerBuffer> TransientMarkerBuffer = new("TransientMarkerBuffer");
        public static readonly ServiceKey<GasPresentationEventBuffer> GasPresentationEventBuffer = new("GasPresentationEventBuffer");
        public static readonly ServiceKey<GlobalPresentationEventBuffer> GlobalPresentationEventBuffer = new("GlobalPresentationEventBuffer");
        public static readonly ServiceKey<GroundOverlayBuffer> GroundOverlayBuffer = new("GroundOverlayBuffer");
        public static readonly ServiceKey<SplineRibbonBuffer> SplineRibbonBuffer = new("SplineRibbonBuffer");
        public static readonly ServiceKey<SoundRequestBuffer> SoundRequestBuffer = new("SoundRequestBuffer");
        public static readonly ServiceKey<DebugDrawCommandBuffer> DebugDrawCommandBuffer = new("DebugDrawCommandBuffer");
        // --- Presenters ---
        public static readonly ServiceKey<PresenterDefinitionRegistry> PresenterDefinitionRegistry = new("PresenterDefinitionRegistry");
        public static readonly ServiceKey<PresenterEntityRuntime> PresenterEntityRuntime = new("PresenterEntityRuntime");
        public static readonly ServiceKey<PresenterAnimatorStateBuffer> PresenterAnimatorStateBuffer = new("PresenterAnimatorStateBuffer");
        public static readonly ServiceKey<SurfaceSourcePayloadRegistry> SurfaceSourcePayloadRegistry = new("SurfaceSourcePayloadRegistry");
        public static readonly ServiceKey<SurfaceSourceRuntimeRegistry> SurfaceSourceRuntimeRegistry = new("SurfaceSourceRuntimeRegistry");

        // --- Spatial ---
        public static readonly ServiceKey<WorldSizeSpec> WorldSizeSpec = new("WorldSizeSpec");
        public static readonly ServiceKey<ISpatialCoordinateConverter> SpatialCoordinateConverter = new("SpatialCoordinateConverter");
        public static readonly ServiceKey<ISpatialQueryService> SpatialQueryService = new("SpatialQueryService");
        public static readonly ServiceKey<HexMetrics> HexMetrics = new("HexMetrics");
        public static readonly ServiceKey<ILoadedChunks> LoadedChunks = new("LoadedChunks");

        // --- Navigation ---
        public static readonly ServiceKey<LoadedGraphRuntime> LoadedGraphRuntime = new("LoadedGraphRuntime");
        public static readonly ServiceKey<GraphEdgeCostOverlay> GraphEdgeCostOverlay = new("GraphEdgeCostOverlay");
        public static readonly ServiceKey<LogicTerrainField> LogicTerrain = new("LogicTerrain");
        public static readonly ServiceKey<AgentProfileRegistry> AgentProfiles = new("AgentProfiles");
        public static readonly ServiceKey<NavMeshBakeConfig> NavMeshBakeConfig = new("NavMeshBakeConfig");
        public static readonly ServiceKey<NavMeshProfileRegistry> NavMeshProfiles = new("NavMeshProfiles");
        public static readonly ServiceKey<NavQueryServiceRegistry> NavQueryServices = new("NavQueryServices");
        public static readonly ServiceKey<INavObstacleAuthoringProvider> NavObstacleAuthoringProvider = new("NavObstacleAuthoringProvider");
        public static readonly ServiceKey<NavObstacleSet> RuntimeNavMeshAuthoredObstacles = new("RuntimeNavMeshAuthoredObstacles");
        public static readonly ServiceKey<NavObstacleSet> RuntimeNavMeshObstacles = new("RuntimeNavMeshObstacles");
        public static readonly ServiceKey<RuntimeIncrementalNavMeshRebuildQueue> RuntimeNavMeshRebuildQueue = new("RuntimeNavMeshRebuildQueue");
        public static readonly ServiceKey<PathingConfig> PathingConfig = new("PathingConfig");
        public static readonly ServiceKey<PathStore> PathStore = new("PathStore");
        public static readonly ServiceKey<IPathService> PathService = new("PathService");

        // --- Client local seats & logical vision (Epic #896) ---
        public static readonly ServiceKey<Ludots.Core.Client.ClientLocalSeatRegistry> ClientLocalSeatRegistry = new("ClientLocalSeatRegistry");
        public static readonly ServiceKey<Ludots.Core.Client.LogicViewRegistry> LogicViewRegistry = new("LogicViewRegistry");
        public static readonly ServiceKey<Entity> TabTargetEntity = new("TabTargetEntity");

        // --- Config & AI ---
        public static readonly ServiceKey<ConfigCatalog> ConfigCatalog = new("ConfigCatalog");
        public static readonly ServiceKey<ConfigConflictReport> ConfigConflictReport = new("ConfigConflictReport");
        public static readonly ServiceKey<RegistrationConflictReport> RegistrationConflictReport = new("RegistrationConflictReport");
        public static readonly ServiceKey<ResolvedModLoadPlan> ModLoadPlan = new("ModLoadPlan");
        public static readonly ServiceKey<AiCompiledRuntime> AiRuntime = new("AiRuntime");

        // --- Diagnostics ---
        public static readonly ServiceKey<ILogBackend> LogBackend = new("LogBackend");
    }
}
