namespace CapabilityStandardPhysics3DShowcaseMod.Runtime;

internal readonly record struct Physics3DShowcasePanelState(
    string Title,
    Physics3DShowcaseScene Scene,
    string SceneTitle,
    string SceneDescription,
    string LastAction,
    bool Paused,
    int FixedHz,
    int PhysicsStepsLastUpdate,
    double PhysicsUpdateMilliseconds,
    double MaximumStepMilliseconds,
    long TotalPhysicsSteps,
    int Bodies,
    int DynamicBodies,
    int KinematicBodies,
    int StaticBodies,
    int AwakeBodies,
    int ContactPairs,
    int ContactEvents,
    int Constraints,
    int VisibleBodies,
    int BenchmarkBodies,
    int BenchmarkPathCount,
    int BenchmarkWaveCount,
    int BenchmarkRecycledBodiesLastStep,
    Physics3DShowcaseReplayStatus ReplayStatus,
    int ReplayCursor,
    int ReplaySteps,
    string QuerySummary,
    string ContactSummary,
    string ReplaySummary,
    string WheelSummary,
    string MaterialSummary,
    string WindSummary,
    string RagdollSummary)
{
    public static Physics3DShowcasePanelState Empty { get; } = new(
        Title: "Physics3D Playground",
        Scene: Physics3DShowcaseScene.ScannerRange,
        SceneTitle: "Inactive",
        SceneDescription: "Load the Physics3D Playground map to begin.",
        LastAction: "No active Physics3D showcase map.",
        Paused: false,
        FixedHz: 0,
        PhysicsStepsLastUpdate: 0,
        PhysicsUpdateMilliseconds: 0d,
        MaximumStepMilliseconds: 0d,
        TotalPhysicsSteps: 0,
        Bodies: 0,
        DynamicBodies: 0,
        KinematicBodies: 0,
        StaticBodies: 0,
        AwakeBodies: 0,
        ContactPairs: 0,
        ContactEvents: 0,
        Constraints: 0,
        VisibleBodies: 0,
        BenchmarkBodies: 0,
        BenchmarkPathCount: 0,
        BenchmarkWaveCount: 0,
        BenchmarkRecycledBodiesLastStep: 0,
        ReplayStatus: Physics3DShowcaseReplayStatus.NotRunning,
        ReplayCursor: 0,
        ReplaySteps: 0,
        QuerySummary: string.Empty,
        ContactSummary: string.Empty,
        ReplaySummary: string.Empty,
        WheelSummary: string.Empty,
        MaterialSummary: string.Empty,
        WindSummary: string.Empty,
        RagdollSummary: string.Empty);
}
