<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Ludots.Core.Physics3DNet</RootNamespace>
    <AssemblyName>Ludots.Physics3DNet</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ludots.Core.csproj" />
    <ProjectReference Include="..\Ludots.Physics3D\Ludots.Physics3D.csproj" />
  </ItemGroup>
</Project>
