#!/usr/bin/env python3
"""Generate per-op GraphNodeOp gallery SSOT from vignettes.

Reads:
  mods/showcases/capability_standard/CapabilityStandardGraphOpsNodeGalleryMod/assets/Vignettes/{Op}.json
Writes/upserts (do not hand-edit these outputs):
  - gallery maps
  - thin entry mods under mods/showcases/capability_standard/graph_op_entries/
  - launcher.config.json bindings
  - launcher.presets.json raylib presets
  - showcase.registry.json entries + gallery csproj exemption
  - assets/Configs/GAS/graph_node_op_coverage.registry.json showcaseId

Subagents own vignettes, FrontDoor graphs, and family driver files only.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PREFIX = "capability_standard_graph_op_"
GALLERY_REL = "mods/showcases/capability_standard/CapabilityStandardGraphOpsNodeGalleryMod"
ENTRY_ROOT_REL = "mods/showcases/capability_standard/graph_op_entries"
COVERAGE_REL = "assets/Configs/GAS/graph_node_op_coverage.registry.json"
ACCEPTANCE = "GraphOpsNodeGalleryAcceptanceTests"
DOCS = "gitbook/architecture/capability-standard-showcases.md"

MAP_TAGS = [
    "showcase",
    "capability-standard",
    "gas",
    "graph-ops",
    "per-op",
]


def merge_field(vignette_dir: Path, vignette: dict) -> dict:
    field = vignette.get("field")
    if not field:
        return vignette
    path = vignette_dir / "_fields" / f"{field}.json"
    if not path.is_file():
        raise SystemExit(f"Vignette field '{field}' missing: {path}")
    scene = load(path)
    merged = dict(vignette)
    if vignette.get("actors"):
        raise SystemExit(
            f"Vignette {vignette.get('op')} sets field '{field}' and also actors; field owns the scene."
        )
    for key in ("actors", "collections", "links"):
        if key in scene:
            merged[key] = scene[key]
    return merged


def actor_to_entity(actor: dict) -> dict:
    x_cm = int(round(float(actor.get("x", 0)) * 100))
    y_cm = int(round(float(actor.get("y", 0)) * 100))
    health = actor.get("health", 100)
    entity = {
        "InstanceId": actor["id"],
        "Template": actor["template"],
        "Overrides": {
            "Name": {"Value": actor["name"]},
            "WorldPositionCm": {"Value": {"X": x_cm, "Y": y_cm}},
            "AttributeBuffer": {"base": {"Health": health}},
        },
    }
    team = actor.get("team")
    if team:
        entity["Overrides"]["Team"] = {"Id": team}
    return entity


def write_map(path: Path, map_id: str, actors: list) -> None:
    if not actors:
        raise SystemExit(f"Map {map_id} has no actors; per-op galleries must spawn people through MapLoader.")
    payload = {
        "Id": map_id,
        "Tags": MAP_TAGS,
        "DefaultCamera": {
            "VirtualCameraId": "Camera.Profile.Tactical",
            "TargetXCm": 0,
            "TargetYCm": 0,
            "DistanceCm": 2600,
            "Pitch": 75,
            "Yaw": 180,
            "FovYDeg": 50,
        },
        "Entities": [actor_to_entity(actor) for actor in actors],
    }
    dump(path, payload)

ENTRY_CSPROJ = """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>{ns}</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\CapabilityStandardGraphOpsNodeGalleryMod\\CapabilityStandardGraphOpsNodeGalleryMod.csproj" />
  </ItemGroup>
</Project>
"""

ENTRY_CS = """using Ludots.Core.Modding;

namespace {ns};

public sealed class {ns}Entry : IMod
{{
    public void OnLoad(IModContext context) {{ }}
    public void OnUnload() {{ }}
}}
"""

ENTRY_MOD_JSON = """{{
  "name": "{ns}",
  "version": "1.0.0",
  "description": "Launcher entry for GraphNodeOp {op} player gallery.",
  "main": "bin/net8.0/{ns}.dll",
  "priority": 0,
  "dependencies": {{
    "CapabilityStandardGraphOpsNodeGalleryMod": "^1.0.0"
  }},
  "tags": [
    "showcase",
    "capability-standard",
    "gas",
    "graph-ops",
    "per-op"
  ]
}}
"""

ENTRY_GAME_JSON = """{{
  "startupMapId": "{map_id}",
  "windowTitle": "Ludots - {title}",
  "targetFps": 60,
  "windowWidth": 1600,
  "windowHeight": 900,
  "windowResizable": true,
  "presentation": {{
    "cameraCulling": {{
      "highLodDistanceCm": 12000,
      "mediumLodDistanceCm": 36000,
      "lowLodDistanceCm": 72000
    }}
  }}
}}
"""

STAMP = "GENERATED by scripts/generate-graph-op-node-galleries.py. Do not hand-edit.\n"


def dump(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def upsert_by_key(items: list, key: str, value: str, entry: dict) -> None:
    for i, item in enumerate(items):
        if isinstance(item, dict) and item.get(key) == value:
            items[i] = entry
            return
    items.append(entry)


def write_entry_mod(repo: Path, op: str, title: str) -> None:
    ns = f"CapabilityStandardGraphOp{op}EntryMod"
    folder = repo / ENTRY_ROOT_REL / ns
    folder.mkdir(parents=True, exist_ok=True)
    map_id = PREFIX + op
    (folder / "GENERATED.txt").write_text(STAMP, encoding="utf-8")
    (folder / f"{ns}.csproj").write_text(ENTRY_CSPROJ.format(ns=ns), encoding="utf-8")
    (folder / f"{ns}Entry.cs").write_text(ENTRY_CS.format(ns=ns), encoding="utf-8")
    (folder / "mod.json").write_text(ENTRY_MOD_JSON.format(ns=ns, op=op), encoding="utf-8")
    assets = folder / "assets"
    assets.mkdir(exist_ok=True)
    (assets / "game.json").write_text(
        ENTRY_GAME_JSON.format(map_id=map_id, title=title.replace('"', '\\"')),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=str(Path(__file__).resolve().parent.parent))
    parser.add_argument("--strict", action="store_true", help="Fail if any coverage op lacks a vignette.")
    args = parser.parse_args()
    repo = Path(args.repo).resolve()
    gallery = repo / GALLERY_REL
    vignette_dir = gallery / "assets" / "Vignettes"
    maps_dir = gallery / "assets" / "Maps"
    maps_dir.mkdir(parents=True, exist_ok=True)

    coverage_path = repo / COVERAGE_REL
    coverage = load(coverage_path)
    ops = [e["op"] for e in coverage["entries"]]
    vignettes = {}
    for path in sorted(vignette_dir.glob("*.json")):
        data = load(path)
        op = data["op"]
        if path.stem != op:
            raise SystemExit(f"Vignette filename {path.name} must match op {op}.")
        vignettes[op] = data

    missing = [op for op in ops if op not in vignettes]
    extra = [op for op in vignettes if op not in ops]
    if extra:
        raise SystemExit(f"Vignettes for unknown ops: {extra}")
    if args.strict and missing:
        raise SystemExit("Missing vignettes:\n" + "\n".join(missing))

    for entry in coverage["entries"]:
        entry["showcaseId"] = PREFIX + entry["op"]
    dump(coverage_path, coverage)

    launcher_path = repo / "launcher.config.json"
    presets_path = repo / "launcher.presets.json"
    registry_path = repo / "showcase.registry.json"
    launcher = load(launcher_path)
    presets = load(presets_path)
    registry = load(registry_path)

    exemptions = registry.setdefault("exemptions", [])
    gallery_exempt = {
        "kind": "csproj",
        "value": GALLERY_REL,
        "reason": "shared per-op GraphNodeOp gallery host; player entries are thin mods under graph_op_entries/",
    }
    if not any(
        isinstance(e, dict) and e.get("kind") == "csproj" and e.get("value") == GALLERY_REL
        for e in exemptions
    ):
        exemptions.append(gallery_exempt)

    showcases = registry.setdefault("showcases", [])
    bindings = launcher.setdefault("bindings", [])
    preset_list = presets.setdefault("presets", [])

    for op, vignette in vignettes.items():
        sid = PREFIX + op
        scene = merge_field(vignette_dir, vignette)
        title = scene["title"]
        beat = scene["beat"]
        ns = f"CapabilityStandardGraphOp{op}EntryMod"
        entry_path = f"{ENTRY_ROOT_REL}/{ns}"
        map_path = maps_dir / f"{sid}.json"
        write_map(map_path, sid, scene.get("actors") or [])
        write_entry_mod(repo, op, title)

        upsert_by_key(
            bindings,
            "name",
            sid,
            {
                "name": sid,
                "target": {
                    "type": "path",
                    "value": entry_path,
                    "projectPath": f"{ns}.csproj",
                },
            },
        )
        upsert_by_key(
            preset_list,
            "id",
            f"{sid}_raylib",
            {
                "id": f"{sid}_raylib",
                "name": f"Graph Op {op} Raylib",
                "selectors": [f"${sid}"],
                "adapterId": "raylib",
                "buildMode": "auto",
            },
        )
        upsert_by_key(
            showcases,
            "id",
            sid,
            {
                "id": sid,
                "path": entry_path,
                "projectPath": f"{ns}.csproj",
                "title": title,
                "summary": beat,
                "tier": "T2",
                "category": "capability",
                "tags": [
                    "graph",
                    "capability-standard",
                    "gas",
                    "graph-ops",
                    "per-op",
                    op,
                ],
                "binding": sid,
                "preset": f"{sid}_raylib",
                "docsPath": DOCS,
                "readmePath": None,
                "acceptanceTest": ACCEPTANCE,
                "artifactDir": f"artifacts/evidence/{sid}",
                "screenshot": None,
                "status": "active",
                "notes": "Per-op player gallery. Recording follows vignette landing.",
            },
        )

    dump(launcher_path, launcher)
    dump(presets_path, presets)
    dump(registry_path, registry)

    print(
        f"Generated {len(vignettes)} per-op galleries; "
        f"coverage showcaseIds updated for {len(ops)} ops; "
        f"missing vignettes: {len(missing)}"
    )
    if missing:
        print("Still missing:")
        for op in missing:
            print(f"  {op}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
