#!/usr/bin/env python3
"""Generate per-feature Ability gallery maps, thin entries, launcher rows, and registry."""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from ability_feature_catalog import (  # noqa: E402
    ACCEPTANCE,
    COVERAGE_REL,
    ENTRY_ROOT_REL,
    FEATURES,
    GALLERY_REL,
    PREFIX,
    WIKI_REL,
)

STAMP = "GENERATED by scripts/generate-ability-feature-galleries.py. Do not hand-edit.\n"

ENTRY_CSPROJ = """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>{ns}</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\CapabilityStandardAbilityFeatureGalleryMod\\CapabilityStandardAbilityFeatureGalleryMod.csproj" />
  </ItemGroup>
</Project>
"""

ENTRY_CS = """using Ludots.Core.Modding;

namespace {ns};

public sealed class {ns}Entry : IMod
{{
    public void OnLoad(IModContext context) {{ }}
    public void OnUnload() {{ }}
}}
"""

ENTRY_MOD_JSON = """{{
  "name": "{ns}",
  "version": "1.0.0",
  "description": "Launcher entry for Ability feature {feature} player gallery.",
  "main": "bin/net9.0/{ns}.dll",
  "priority": 0,
  "dependencies": {{
    "CapabilityStandardAbilityFeatureGalleryMod": "^1.0.0"
  }},
  "tags": [
    "showcase",
    "capability-standard",
    "gas",
    "ability",
    "per-feature"
  ]
}}
"""

ENTRY_GAME_JSON = """{{
  "startupMapId": "{map_id}",
  "windowTitle": "Ludots - {title}",
  "targetFps": 60,
  "windowWidth": 1600,
  "windowHeight": 900,
  "windowResizable": true
}}
"""


def dump(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def upsert_by_key(items: list, key: str, value: str, entry: dict) -> None:
    for i, item in enumerate(items):
        if isinstance(item, dict) and item.get(key) == value:
            items[i] = entry
            return
    items.append(entry)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def caster_overrides(feature: dict) -> dict:
    abilities = feature.get("casterAbilities") or [feature["abilityId"]]
    overrides = {
        "Name": {"Value": "施法者"},
        "AbilityStateBuffer": {"abilityIds": abilities},
    }
    if feature.get("formSetId"):
        overrides["AbilityFormSetRef"] = {"formSetId": feature["formSetId"]}
    if feature.get("needsProgression"):
        overrides["ProgressionScopeBinding"] = {
            "entries": [{"scope": "abilityfeature.self", "hostKey": "ability_feature_board"}]
        }
    return overrides


def write_map(path: Path, feature: dict) -> None:
    sid = PREFIX + feature["feature"]
    entities = [
        {
            "InstanceId": "caster",
            "Template": "AbilityFeature.Caster",
            "Overrides": caster_overrides(feature),
        },
        {
            "InstanceId": "target",
            "Template": "AbilityFeature.Dummy",
            "Overrides": {
                "Name": {"Value": "木桩"},
                "WorldPositionCm": {"Value": {"X": 5600, "Y": 5000}},
            },
        },
    ]
    extra = feature.get("extraActors") or []
    if "target2" in extra:
        entities.append(
            {
                "InstanceId": "target2",
                "Template": "AbilityFeature.Dummy",
                "Overrides": {
                    "Name": {"Value": "远木桩"},
                    "WorldPositionCm": {"Value": {"X": 6400, "Y": 5000}},
                },
            }
        )
    if "wounded" in extra:
        entities.append(
            {
                "InstanceId": "wounded",
                "Template": "AbilityFeature.Wounded",
                "Overrides": {"Name": {"Value": "残血木桩"}},
            }
        )
    if feature.get("needsProgression"):
        entities.append({"InstanceId": "unlock-board", "Template": "AbilityFeature.UnlockBoard"})

    dump(
        path,
        {
            "Id": sid,
            "Tags": ["showcase", "capability-standard", "gas", "ability", "per-feature", feature["feature"]],
            "DefaultCamera": {
                "TargetXCm": 5200,
                "TargetYCm": 5000,
                "Yaw": 180,
                "Pitch": 50,
                "DistanceCm": 6400,
                "FovYDeg": 60,
            },
            "Boards": [
                {
                    "Name": "default",
                    "SpatialType": "HexGrid",
                    "WidthInMacroTiles": 32,
                    "HeightInMacroTiles": 32,
                    "HexEdgeLengthCm": 400,
                    "ChunkSizeCells": 32,
                    "NavigationEnabled": False,
                }
            ],
            "Entities": entities,
            "Teams": [
                {"TeamId": 1, "RepresentativeInstanceId": "caster"},
                {"TeamId": 2, "RepresentativeInstanceId": "target"},
            ],
            "Players": [
                {"PlayerId": 1, "TeamId": 1, "RepresentativeInstanceId": "caster"},
                {"PlayerId": 2, "TeamId": 2, "RepresentativeInstanceId": "target"},
            ],
        },
    )


def write_entry(repo: Path, feature: dict) -> None:
    name = feature["feature"]
    ns = f"CapabilityStandardAbilityFeature{name}EntryMod"
    folder = repo / ENTRY_ROOT_REL / ns
    folder.mkdir(parents=True, exist_ok=True)
    write_text(folder / "GENERATED.txt", STAMP)
    write_text(folder / f"{ns}.csproj", ENTRY_CSPROJ.format(ns=ns))
    write_text(folder / f"{ns}Entry.cs", ENTRY_CS.format(ns=ns))
    write_text(folder / "mod.json", ENTRY_MOD_JSON.format(ns=ns, feature=name))
    write_text(
        folder / "assets" / "game.json",
        ENTRY_GAME_JSON.format(map_id=PREFIX + name, title=feature["title"].replace('"', '\\"')),
    )


def remove_orphans(repo: Path, live: set[str], maps_dir: Path, bindings: list, presets: list, showcases: list) -> int:
    live_ids = {PREFIX + name for name in live}
    removed = 0
    for path in list(maps_dir.glob("*.json")):
        if path.stem.startswith(PREFIX) and path.stem not in live_ids:
            path.unlink()
            removed += 1
    entry_root = repo / ENTRY_ROOT_REL
    if entry_root.is_dir():
        for folder in list(entry_root.iterdir()):
            if not folder.name.startswith("CapabilityStandardAbilityFeature") or not folder.name.endswith("EntryMod"):
                continue
            feature = folder.name[len("CapabilityStandardAbilityFeature") : -len("EntryMod")]
            if feature not in live:
                shutil.rmtree(folder)
                removed += 1
    bindings[:] = [b for b in bindings if not (str(b.get("name", "")).startswith(PREFIX) and b.get("name") not in live_ids)]
    presets[:] = [
        p
        for p in presets
        if not (
            str(p.get("id", "")).startswith(PREFIX)
            and p.get("id", "").removesuffix("_raylib") not in live_ids
        )
    ]
    showcases[:] = [s for s in showcases if not (str(s.get("id", "")).startswith(PREFIX) and s.get("id") not in live_ids)]
    return removed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=str(Path(__file__).resolve().parent.parent))
    args = parser.parse_args()
    repo = Path(args.repo).resolve()
    gallery = repo / GALLERY_REL
    maps_dir = gallery / "assets" / "Maps"
    maps_dir.mkdir(parents=True, exist_ok=True)

    launcher = load(repo / "launcher.config.json")
    presets = load(repo / "launcher.presets.json")
    registry = load(repo / "showcase.registry.json")
    exemptions = registry.setdefault("exemptions", [])
    gallery_exempt = {
        "kind": "csproj",
        "value": GALLERY_REL,
        "reason": "shared per-feature Ability gallery host; player entries are thin mods under ability_feature_entries/",
    }
    if not any(isinstance(e, dict) and e.get("kind") == "csproj" and e.get("value") == GALLERY_REL for e in exemptions):
        exemptions.append(gallery_exempt)

    bindings = launcher.setdefault("bindings", [])
    preset_list = presets.setdefault("presets", [])
    showcases = registry.setdefault("showcases", [])
    live = {f["feature"] for f in FEATURES}

    for feature in FEATURES:
        sid = PREFIX + feature["feature"]
        write_map(maps_dir / f"{sid}.json", feature)
        write_entry(repo, feature)
        ns = f"CapabilityStandardAbilityFeature{feature['feature']}EntryMod"
        entry_path = f"{ENTRY_ROOT_REL}/{ns}"
        upsert_by_key(
            bindings,
            "name",
            sid,
            {"name": sid, "target": {"type": "path", "value": entry_path, "projectPath": f"{ns}.csproj"}},
        )
        upsert_by_key(
            preset_list,
            "id",
            f"{sid}_raylib",
            {
                "id": f"{sid}_raylib",
                "name": feature["title"],
                "selectors": [f"${sid}"],
                "adapterId": "raylib",
                "buildMode": "auto",
            },
        )
        evidence = f"artifacts/evidence/{sid}"
        upsert_by_key(
            showcases,
            "id",
            sid,
            {
                "id": sid,
                "path": entry_path,
                "projectPath": f"{ns}.csproj",
                "title": feature["title"],
                "summary": feature["beat"],
                "tier": "T2",
                "category": "capability",
                "tags": ["capability-standard", "gas", "ability", "per-feature", feature["feature"]],
                "binding": sid,
                "preset": f"{sid}_raylib",
                "docsPath": f"{WIKI_REL}/{feature['feature']}.md",
                "readmePath": None,
                "acceptanceTest": ACCEPTANCE,
                "artifactDir": evidence,
                "screenshot": None,
                "status": "active",
                "notes": "Per-feature Ability player gallery. Wiki under ability-feature-wiki; video evidence pending recording.",
            },
        )

    removed = remove_orphans(repo, live, maps_dir, bindings, preset_list, showcases)
    mark_champion_as_ensemble(showcases)
    launcher["bindings"] = bindings
    presets["presets"] = preset_list
    dump(repo / "launcher.config.json", launcher)
    dump(repo / "launcher.presets.json", presets)
    dump(repo / "showcase.registry.json", registry)
    write_coverage(repo)
    print(f"Generated {len(FEATURES)} ability feature galleries; removed {removed} orphans.")
    return 0


def mark_champion_as_ensemble(showcases: list) -> None:
    for item in showcases:
        if isinstance(item, dict) and item.get("id") == "champion_skill_sandbox":
            item["summary"] = "把多招串成一栏的组合戏，不是技能词条入口。词条进 capability_standard_ability_feature_*。"
            item["notes"] = "组合戏。技能词条画廊是 capability_standard_ability_feature_*。"
            tags = item.setdefault("tags", [])
            if "ensemble" not in tags:
                tags.append("ensemble")
            return


def write_coverage(repo: Path) -> None:
    dump(
        repo / COVERAGE_REL,
        {
            "description": (
                "Ability feature coverage SSOT. Each covered contract has a per-feature "
                "showcaseId and must be exercised by AbilityFeatureGalleryAcceptanceTests."
            ),
            "entries": [
                {
                    "feature": feature["feature"],
                    "showcaseId": PREFIX + feature["feature"],
                    "status": "covered",
                    "family": feature["family"],
                    "acceptanceTest": ACCEPTANCE,
                }
                for feature in FEATURES
            ],
        },
    )


if __name__ == "__main__":
    raise SystemExit(main())
