# -*- coding: utf-8 -*-
"""Unique player-action index + platform variants (SSOT).

Each ACTION_GROUP is one semantic interaction (UX-NNN).
Members are platform implementations (gamepad / kbm / touch) that share the same intent.
Consumed by generate-player-action-ux-catalog.py — do not hand-edit catalog-data.js.
"""
from __future__ import annotations

PLATFORM_ORDER = ("gamepad", "kbm", "touch")
PLATFORM_LABEL = {
    "gamepad": "主机",
    "kbm": "键鼠",
    "touch": "触控",
}

# (actionNo, key, title, ((case_id, platform), ...))
ACTION_GROUPS: list[tuple[str, str, str, tuple[tuple[str, str], ...]]] = [
    ("UX-001", "drag-aim-skill", "拖指示器松手放技能", (("skill-ground-drag-release", "kbm"), ("touch-drag-aim-skill", "touch"),)),
    ("UX-002", "select-unit", "点选一个单位", (("select-click", "kbm"), ("touch-tap-select-unit", "touch"),)),
    ("UX-003", "loco-relative-walk", "相对镜头方向行走", (("loco-stick-walk", "gamepad"), ("loco-wasd-camera", "kbm"),)),
    ("UX-004", "twin-move-aim", "移瞄分离移动射击", (("twin-move-aim-split", "gamepad"), ("twin-kb-mouse-equiv", "kbm"),)),
    ("UX-005", "hold-context-menu", "长按出上下文菜单", (("ui-hold-context-menu", "kbm"), ("touch-longpress-info", "touch"),)),
    ("UX-006", "habit-alt-self", "Alt对自己放", (("habit-alt-self", "kbm"),)),
    ("UX-007", "context-ra2-rightclick", "RA2右键随兵种变化", (("context-ra2-rightclick", "kbm"),)),
    ("UX-008", "temp-kit-rts-morph-ability", "RTS限时形态换面板", (("temp-kit-rts-morph-ability", "kbm"),)),
    ("UX-009", "context-sc2-rightclick", "SC2右键随选中变化", (("context-sc2-rightclick", "kbm"),)),
    ("UX-010", "habit-shift-queue-cast", "Shift排队施法", (("habit-shift-queue-cast", "kbm"),)),
    ("UX-011", "mmo-tab-target", "按Tab轮换敌方目标", (("mmo-tab-target", "kbm"),)),
    ("UX-012", "loco-wasd-vs-click", "WASD与点地谁优先", (("loco-wasd-vs-click", "kbm"),)),
    ("UX-013", "army-vehicle", "上车变载具手感", (("army-vehicle", "gamepad"),)),
    ("UX-014", "army-merge", "两单位合体", (("army-merge", "kbm"),)),
    ("UX-015", "combo-recast-stages", "两段技能再按", (("combo-recast-stages", "kbm"),)),
    ("UX-016", "hold-block-channel", "举盾或站桩引导", (("hold-block-channel", "kbm"),)),
    ("UX-017", "mmo-trade", "交易窗双边确认", (("mmo-trade", "kbm"),)),
    ("UX-018", "mmo-quest-tracker", "任务追踪去地图", (("mmo-quest-tracker", "kbm"),)),
    ("UX-019", "loco-strafe-backpedal", "侧移与后撤", (("loco-strafe-backpedal", "kbm"),)),
    ("UX-020", "ui-ping-comm-wheel", "信号沟通轮", (("ui-ping-comm-wheel", "kbm"),)),
    ("UX-021", "dyn-ctx-downed-ally", "倒地队友解锁救援", (("dyn-ctx-downed-ally", "kbm"),)),
    ("UX-022", "order-stop-hold", "停止或原地坚守", (("order-stop-hold", "kbm"),)),
    ("UX-023", "temp-kit-steal-copy", "偷来或复制的技能", (("temp-kit-steal-copy", "kbm"),)),
    ("UX-024", "loco-sprint", "冲刺跑步", (("loco-sprint", "kbm"),)),
    ("UX-025", "block-cooldown", "冷却中拒绝", (("block-cooldown", "kbm"),)),
    ("UX-026", "menu-rotk-layered", "分层选单下指令", (("menu-rotk-layered", "kbm"),)),
    ("UX-027", "select-possess", "切换操控对象", (("select-possess", "kbm"),)),
    ("UX-028", "select-add-sub", "加选减选反选", (("select-add-sub", "kbm"),)),
    ("UX-029", "ui-confirm-destructive", "危险操作二次确认", (("ui-confirm-destructive", "kbm"),)),
    ("UX-030", "habit-double-tap", "双击技能变体", (("habit-double-tap", "kbm"),)),
    ("UX-031", "select-double-type", "双击选同类型", (("select-double-type", "kbm"),)),
    ("UX-032", "touch-pinch-pan", "双指缩放单指拖图", (("touch-pinch-pan", "touch"),)),
    ("UX-033", "select-clear", "取消全部选中", (("select-clear", "kbm"),)),
    ("UX-034", "temp-kit-gow-transform", "变身临时整栏技能", (("temp-kit-gow-transform", "kbm"),)),
    ("UX-035", "skill-ally-only", "只能点特定对象", (("skill-ally-only", "kbm"),)),
    ("UX-036", "twin-fire-on-aim", "右摇杆推出即开火", (("twin-fire-on-aim", "gamepad"),)),
    ("UX-037", "twin-stick-magnets", "右摇杆磁吸辅助", (("twin-stick-magnets", "gamepad"),)),
    ("UX-038", "context-ground-vs-object", "右键地面对比对象", (("context-ground-vs-object", "kbm"),)),
    ("UX-039", "atk-right-click-enemy", "右键敌人下令攻击", (("atk-right-click-enemy", "kbm"),)),
    ("UX-040", "order-smart-right", "右键智能指令", (("order-smart-right", "kbm"),)),
    ("UX-041", "dyn-ctx-same-key-swap", "同键随情境换动词", (("dyn-ctx-same-key-swap", "kbm"),)),
    ("UX-042", "army-pet-attack", "命令随从打目标", (("army-pet-attack", "kbm"),)),
    ("UX-043", "mmo-vendor", "商人买卖回购", (("mmo-vendor", "kbm"),)),
    ("UX-044", "item-need-greed", "团队掷骰分配", (("item-need-greed", "kbm"),)),
    ("UX-045", "item-pickup-world", "地上捡东西", (("item-pickup-world", "kbm"),)),
    ("UX-046", "mmo-mount-taxi", "坐骑与飞行点", (("mmo-mount-taxi", "kbm"),)),
    ("UX-047", "multi-cast-split-targets", "多人各打一目标", (("multi-cast-split-targets", "kbm"),)),
    ("UX-048", "auto-cast-priority-multi", "多自动技能优先级", (("auto-cast-priority-multi", "kbm"),)),
    ("UX-049", "multi-cast-priority", "多选按优先级放", (("multi-cast-priority", "kbm"),)),
    ("UX-050", "multi-cast-sequence", "多选按序施放", (("multi-cast-sequence", "kbm"),)),
    ("UX-051", "multi-cast-together", "多选齐放", (("multi-cast-together", "kbm"),)),
    ("UX-052", "dyn-ctx-priority-overlap", "多重交互抢提示", (("dyn-ctx-priority-overlap", "kbm"),)),
    ("UX-053", "ui-map-waypoint", "大地图钉点导航", (("ui-map-waypoint", "kbm"),)),
    ("UX-054", "select-lasso", "套索圈选单位", (("select-lasso", "kbm"),)),
    ("UX-055", "def-perfect-dodge", "完美闪避", (("def-perfect-dodge", "kbm"),)),
    ("UX-056", "auto-cast-pet-ability", "宝宝召唤物自动技", (("auto-cast-pet-ability", "kbm"),)),
    ("UX-057", "mmo-whisper-mark", "密聊与标记目标", (("mmo-whisper-mark", "kbm"),)),
    ("UX-058", "mmo-interact-npc", "对NPC按交互", (("mmo-interact-npc", "kbm"),)),
    ("UX-059", "item-use-on-ground", "对地面用物品", (("item-use-on-ground", "kbm"),)),
    ("UX-060", "item-use-on-target", "对目标用物品", (("item-use-on-target", "kbm"),)),
    ("UX-061", "item-use-self", "对自己用消耗品", (("item-use-self", "kbm"),)),
    ("UX-062", "mmo-dialogue-choice", "对话选项与跳过", (("mmo-dialogue-choice", "kbm"),)),
    ("UX-063", "skill-minimap-ground", "小地图点落点", (("skill-minimap-ground", "kbm"),)),
    ("UX-064", "order-patrol-rally", "巡逻与集结点", (("order-patrol-rally", "kbm"),)),
    ("UX-065", "ui-build-tech-click", "建造科技树点击", (("ui-build-tech-click", "kbm"),)),
    ("UX-066", "skill-build-place", "建造落格", (("skill-build-place", "kbm"),)),
    ("UX-067", "skill-toggle-form", "开关姿态切形态", (("skill-toggle-form", "kbm"),)),
    ("UX-068", "item-loot-window", "开箱或尸体掉落窗", (("item-loot-window", "kbm"),)),
    ("UX-069", "atk-ads-reload-swap", "开镜换弹切枪", (("atk-ads-reload-swap", "kbm"),)),
    ("UX-070", "def-parry-window", "弹反窗与反击", (("def-parry-window", "kbm"),)),
    ("UX-071", "temp-kit-empower-next", "强化下一击", (("temp-kit-empower-next", "kbm"),)),
    ("UX-072", "context-stance-changes-verb", "形态变右键也变", (("context-stance-changes-verb", "kbm"),)),
    ("UX-073", "item-compare-tooltip", "悬停装备对比", (("item-compare-tooltip", "kbm"),)),
    ("UX-074", "skill-cone-sweep", "扇形扫射预览", (("skill-cone-sweep", "kbm"),)),
    ("UX-075", "auto-cast-vs-manual-preempt", "手动抢按让路", (("auto-cast-vs-manual-preempt", "kbm"),)),
    ("UX-076", "env-destructible", "打可破坏物", (("env-destructible", "kbm"),)),
    ("UX-077", "mmo-interrupt-cast", "打断或取消读条", (("mmo-interrupt-cast", "kbm"),)),
    ("UX-078", "atk-grenade", "扔手雷到落点", (("atk-grenade", "kbm"),)),
    ("UX-079", "skill-ground-click", "技能后点地板", (("skill-ground-click", "kbm"),)),
    ("UX-080", "skill-pick-enemy", "技能后点敌人", (("skill-pick-enemy", "kbm"),)),
    ("UX-081", "menu-grid-command-panel", "技能格面板点选", (("menu-grid-command-panel", "kbm"),)),
    ("UX-082", "auto-cast-toggle-ability", "技能自动施法开关", (("auto-cast-toggle-ability", "kbm"),)),
    ("UX-083", "item-split-stack", "拆堆与合堆", (("item-split-stack", "kbm"),)),
    ("UX-084", "skill-vector", "拉矢量再放", (("skill-vector", "kbm"),)),
    ("UX-085", "item-hotbar-drag", "拖到快捷栏", (("item-hotbar-drag", "kbm"),)),
    ("UX-086", "touch-drag-deploy-card", "拖拽手牌部署", (("touch-drag-deploy-card", "touch"),)),
    ("UX-087", "select-box", "拖框选一群单位", (("select-box", "kbm"),)),
    ("UX-088", "dyn-ctx-held-item-verb", "持有物改变交互动词", (("dyn-ctx-held-item-verb", "kbm"),)),
    ("UX-089", "skill-dash-dir", "指定方向冲刺", (("skill-dash-dir", "kbm"),)),
    ("UX-090", "ui-hold-vs-toggle", "按住与切换手感", (("ui-hold-vs-toggle", "kbm"),)),
    ("UX-091", "atk-melee-hold-chain", "按住打连段", (("atk-melee-hold-chain", "kbm"),)),
    ("UX-092", "hold-full-auto", "按住持续扫射", (("hold-full-auto", "kbm"),)),
    ("UX-093", "ui-radial-wheel", "按住轮盘松手选定", (("ui-radial-wheel", "gamepad"),)),
    ("UX-094", "auto-cast-assist-repeat", "按住辅助连放", (("auto-cast-assist-repeat", "kbm"),)),
    ("UX-095", "skill-self-buff", "按键自身状态", (("skill-self-buff", "kbm"),)),
    ("UX-096", "env-throw", "捡起东西扔掉", (("env-throw", "kbm"),)),
    ("UX-097", "order-queue", "排队一串指令", (("order-queue", "kbm"),)),
    ("UX-098", "item-destroy-sell", "摧毁或卖店", (("item-destroy-sell", "kbm"),)),
    ("UX-099", "order-attack-move", "攻击移动", (("order-attack-move", "kbm"),)),
    ("UX-100", "ui-tutorial-prompt", "教学逼迫输入", (("ui-tutorial-prompt", "kbm"),)),
    ("UX-101", "twin-auto-face", "无瞄准时的朝向", (("twin-auto-face", "gamepad"),)),
    ("UX-102", "habit-smart-vs-normal", "智能施法与先瞄后放", (("habit-smart-vs-normal", "kbm"),)),
    ("UX-103", "skill-smart-cast-unit", "智能施法打准星单位", (("skill-smart-cast-unit", "kbm"),)),
    ("UX-104", "skill-blink-facing", "朝面向闪现", (("skill-blink-facing", "kbm"),)),
    ("UX-105", "auto-cast-condition-script", "条件触发自动", (("auto-cast-condition-script", "kbm"),)),
    ("UX-106", "loco-release-stop", "松键停与惯性", (("loco-release-stop", "kbm"),)),
    ("UX-107", "atk-gun-tap-spray", "枪械点射扫射", (("atk-gun-tap-spray", "kbm"),)),
    ("UX-108", "ui-drag-drop-slot", "槽位拖放", (("ui-drag-drop-slot", "kbm"),)),
    ("UX-109", "item-charges-durability", "次数道具与耐久", (("item-charges-durability", "kbm"),)),
    ("UX-110", "select-avatar-only", "永远只操控自己", (("select-avatar-only", "kbm"),)),
    ("UX-111", "context-mixed-selection", "混选右键各干各的", (("context-mixed-selection", "kbm"),)),
    ("UX-112", "touch-card-cycle", "滑动切换手牌", (("touch-card-cycle", "touch"),)),
    ("UX-113", "loco-click-move-avatar", "点地只指挥自己", (("loco-click-move-avatar", "kbm"),)),
    ("UX-114", "dyn-ctx-state-threshold", "状态到线才解锁", (("dyn-ctx-state-threshold", "kbm"),)),
    ("UX-115", "dyn-ctx-env-ledge-cover", "环境位姿解锁互动", (("dyn-ctx-env-ledge-cover", "kbm"),)),
    ("UX-116", "aim-cancel", "瞄准中取消", (("aim-cancel", "kbm"),)),
    ("UX-117", "env-wall-slam", "砸墙或推悬崖", (("env-wall-slam", "kbm"),)),
    ("UX-118", "aim-hard-lock", "硬锁定切换目标", (("aim-hard-lock", "gamepad"),)),
    ("UX-119", "temp-kit-shrine-zone", "神龛区域临时技", (("temp-kit-shrine-zone", "kbm"),)),
    ("UX-120", "item-equip-swap", "穿脱替换装备", (("item-equip-swap", "kbm"),)),
    ("UX-121", "mmo-party-invite", "组队邀请接受离队", (("mmo-party-invite", "kbm"),)),
    ("UX-122", "def-dodge", "翻滚闪避", (("def-dodge", "kbm"),)),
    ("UX-123", "ui-inventory-tetris", "背包异形摆放", (("ui-inventory-tetris", "kbm"),)),
    ("UX-124", "block-bag-full", "背包满拒绝", (("block-bag-full", "kbm"),)),
    ("UX-125", "loco-autorun", "自动前进锁W", (("loco-autorun", "kbm"),)),
    ("UX-126", "mmo-auto-attack", "自动攻击开关", (("mmo-auto-attack", "kbm"),)),
    ("UX-127", "auto-cast-attack-assist", "自动普攻与技能自动", (("auto-cast-attack-assist", "kbm"),)),
    ("UX-128", "skill-self-aoe", "自己脚下炸一圈", (("skill-self-aoe", "kbm"),)),
    ("UX-129", "menu-confirm-queue", "菜单确认后入队", (("menu-confirm-queue", "kbm"),)),
    ("UX-130", "hold-charge-shot", "蓄力松手开火", (("hold-charge-shot", "kbm"),)),
    ("UX-131", "mmo-emote-sit", "表情坐下检查", (("mmo-emote-sit", "kbm"),)),
    ("UX-132", "block-crowd-control", "被控无法操作", (("block-crowd-control", "kbm"),)),
    ("UX-133", "order-load-unload", "装载与卸载", (("order-load-unload", "kbm"),)),
    ("UX-134", "ui-spectate-replay", "观战回放切视角", (("ui-spectate-replay", "kbm"),)),
    ("UX-135", "dyn-ctx-angle-stealth", "角度潜行才解锁", (("dyn-ctx-angle-stealth", "kbm"),)),
    ("UX-136", "select-control-group", "记编队与召编队", (("select-control-group", "kbm"),)),
    ("UX-137", "block-resource", "资源不足拒绝", (("block-resource", "kbm"),)),
    ("UX-138", "order-move", "走到地上一点", (("order-move", "kbm"),)),
    ("UX-139", "block-range-los-trade", "超距遮挡条件不足", (("block-range-los-trade", "kbm"),)),
    ("UX-140", "mmo-follow-assist", "跟随与协助", (("mmo-follow-assist", "kbm"),)),
    ("UX-141", "loco-wasd-tank", "车式转向行走", (("loco-wasd-tank", "kbm"),)),
    ("UX-142", "aim-look", "转动视角准星", (("aim-look-stick", "gamepad"), ("aim-look", "kbm"))),
    ("UX-143", "aim-soft-lock", "软锁定附近敌人", (("aim-soft-lock", "gamepad"),)),
    ("UX-144", "combo-light-chain", "轻攻击连段", (("combo-light-chain", "kbm"),)),
    ("UX-145", "combo-heavy-branch", "轻重混按分支", (("combo-heavy-branch", "kbm"),)),
    ("UX-146", "temp-kit-vehicle-gunner", "载具炮台替换操作", (("temp-kit-vehicle-gunner", "gamepad"),)),
    ("UX-147", "atk-melee-tap", "近战点一下", (("atk-melee-tap", "kbm"),)),
    ("UX-148", "aim-skill-indicator", "进入技能瞄准", (("aim-skill-indicator", "kbm"),)),
    ("UX-149", "auto-cast-when-in-range", "进距才自动施放", (("auto-cast-when-in-range", "kbm"),)),
    ("UX-150", "skill-two-targets", "连续点两个目标", (("skill-two-targets", "kbm"),)),
    ("UX-151", "skill-direction-shot", "选方向射出", (("skill-direction-shot", "kbm"),)),
    ("UX-152", "mmo-mailbox-ah", "邮箱与拍卖行", (("mmo-mailbox-ah", "kbm"),)),
    ("UX-153", "mmo-gather-channel", "采集读条", (("mmo-gather-channel", "kbm"),)),
    ("UX-154", "mmo-release-resurrect", "释放灵魂与复活", (("mmo-release-resurrect", "kbm"),)),
    ("UX-155", "skill-grapple", "钩索荡出去", (("skill-grapple", "kbm"),)),
    ("UX-156", "ui-camera-modes", "镜头模式切换", (("ui-camera-modes", "kbm"),)),
    ("UX-157", "twin-dodge-shoot", "闪避中转向射击", (("twin-dodge-shoot", "gamepad"),)),
    ("UX-158", "combo-dodge-attack", "闪避后接攻击", (("combo-dodge-attack", "kbm"),)),
    ("UX-159", "temp-kit-timed-overlay", "限时叠加临时键", (("temp-kit-timed-overlay", "kbm"),)),
    ("UX-160", "block-fog-illegal", "雾中或类型非法", (("block-fog-illegal", "kbm"),)),
    ("UX-161", "dyn-ctx-vehicle-board", "靠近载具解锁上车", (("dyn-ctx-vehicle-board", "kbm"),)),
    ("UX-162", "temp-kit-item-trinket", "饰品道具主动技", (("temp-kit-item-trinket", "kbm"),)),
    ("UX-163", "temp-kit-mount-combat", "骑乘战斗临时键", (("temp-kit-mount-combat", "kbm"),)),
    # ---- 联机多人 ----
    ("UX-164", "net-create-join-room", "建房或输房号加入", (("net-create-join-room", "kbm"),)),
    ("UX-165", "net-lobby-ready", "大厅准备全绿才开局", (("net-lobby-ready", "kbm"),)),
    ("UX-166", "net-matchmaking-queue", "匹配排队与限时接受", (("net-matchmaking-queue", "kbm"),)),
    ("UX-167", "net-disconnect-reconnect", "我掉线后的重连", (("net-disconnect-reconnect", "kbm"),)),
    ("UX-168", "net-teammate-drop-ai", "队友掉线与AI托管", (("net-teammate-drop-ai", "kbm"),)),
    ("UX-169", "net-lag-rollback", "延迟把我拉回原位", (("net-lag-rollback", "kbm"),)),
    ("UX-170", "net-push-to-talk", "按住说话与麦克风开关", (("net-push-to-talk", "kbm"),)),
    ("UX-171", "net-surrender-vote", "发起投降与队伍表决", (("net-surrender-vote", "kbm"),)),
    ("UX-172", "net-report-mute", "屏蔽或举报某个玩家", (("net-report-mute", "kbm"),)),
    ("UX-173", "net-crossplay-prompt", "跨平台同队各按各的键",
     (("net-crossplay-prompt-pad", "gamepad"), ("net-crossplay-prompt-kbm", "kbm"))),
    # ---- 同屏多人 ----
    ("UX-174", "couch-pad-join", "第二个手柄按键加入", (("couch-pad-join", "gamepad"),)),
    ("UX-175", "couch-pad-drop", "手柄断开与接回原角色", (("couch-pad-drop", "gamepad"),)),
    ("UX-176", "couch-split-mode", "分屏方式切换", (("couch-split-mode", "gamepad"),)),
    ("UX-177", "couch-shared-camera-tether", "共享单屏被镜头拉住",
     (("couch-shared-camera-tether", "gamepad"),)),
    ("UX-178", "couch-loot-race", "同屏抢同一个东西", (("couch-loot-race", "gamepad"),)),
    ("UX-179", "couch-menu-owner", "同屏共用菜单归谁操作", (("couch-menu-owner", "gamepad"),)),
    ("UX-180", "couch-mixed-devices", "一台机器两种设备各控一角",
     (("couch-mixed-devices-pad", "gamepad"), ("couch-mixed-devices-kbm", "kbm"))),
    # ---- 从 UX-011 拆出来：用界面选人和用键盘轮换敌人是两条路 ----
    ("UX-181", "mmo-party-frame-target", "点队友头像选中他",
     (("mmo-party-frame-target", "kbm"),)),
    # ---- 打到一半目标没了 ----
    ("UX-182", "target-lost-out-of-range", "目标跑远锁定自动松开",
     (("target-lost-out-of-range", "kbm"),)),
    ("UX-183", "target-lost-invalid-mid-cast", "读条中目标失效并回滚",
     (("target-lost-invalid-mid-cast", "kbm"),)),
    # ---- 回合制：轮到我之前和之后 ----
    ("UX-184", "turn-order-timeline", "看行动条谁下一个", (("turn-order-timeline", "kbm"),)),
    ("UX-185", "turn-undo-before-confirm", "确认前都能退回来", (("turn-undo-before-confirm", "kbm"),)),
    ("UX-186", "turn-delay-action", "延后行动等时机", (("turn-delay-action", "kbm"),)),
    ("UX-187", "turn-enemy-intent", "敌人预告下一步", (("turn-enemy-intent", "kbm"),)),
    ("UX-188", "turn-insert-cutin", "插队改出手顺序", (("turn-insert-cutin", "kbm"),)),
    # ---- 战棋：格子、朝向、控制区 ----
    ("UX-189", "srpg-move-range-path", "移动范围与路径花费", (("srpg-move-range-path", "kbm"),)),
    ("UX-190", "srpg-facing-backstab", "朝向决定伤害", (("srpg-facing-backstab", "kbm"),)),
    ("UX-191", "srpg-zone-of-control", "踩进控制区被迫停下", (("srpg-zone-of-control", "kbm"),)),
    ("UX-192", "srpg-tile-occupied", "目标格被占怎么办", (("srpg-tile-occupied", "kbm"),)),
    ("UX-193", "srpg-height-cover", "格子的高低与掩体", (("srpg-height-cover", "kbm"),)),
    # ---- 大战略：对抽象东西下手 ----
    ("UX-194", "gs-cast-on-region", "把一件事派到某个省", (("gs-cast-on-region", "kbm"),)),
    ("UX-195", "gs-cast-on-relation", "对两方之间的关系下手", (("gs-cast-on-relation", "kbm"),)),
    ("UX-196", "gs-cast-on-faction", "对派系游说", (("gs-cast-on-faction", "kbm"),)),
    ("UX-197", "gs-enact-law", "颁布法令改规则", (("gs-enact-law", "kbm"),)),
    ("UX-198", "gs-abstract-cost", "代价是威望与影响力", (("gs-abstract-cost", "kbm"),)),
    ("UX-199", "gs-tiered-scope", "生效范围是行政层级", (("gs-tiered-scope", "kbm"),)),
    # ---- 技能的时机 ----
    ("UX-200", "ab-input-buffer", "后摆里提前按会被记住", (("ab-input-buffer", "kbm"),)),
    ("UX-201", "ab-cancel-recovery", "用闪避砍掉自己的后摆", (("ab-cancel-recovery", "kbm"),)),
    ("UX-202", "ab-delayed-aoe", "先标地面过一会才炸", (("ab-delayed-aoe", "kbm"),)),
    ("UX-203", "ab-reactive-trigger", "被打那一下自动触发", (("ab-reactive-trigger", "kbm"),)),
    # ---- 技能的代价 ----
    ("UX-204", "ab-charges-stack", "攒层数能连按几次", (("ab-charges-stack", "kbm"),)),
    ("UX-205", "ab-global-cooldown", "全局冷却压住整栏", (("ab-global-cooldown", "kbm"),)),
    ("UX-206", "ab-hp-cost", "拿血当代价", (("ab-hp-cost", "kbm"),)),
    ("UX-207", "ab-cost-on-resolve", "按下就扣还是打中才扣", (("ab-cost-on-resolve", "kbm"),)),
    # ---- 技能打出去之后 ----
    ("UX-208", "ab-miss-vs-immune", "没打中和被免疫是两回事", (("ab-miss-vs-immune", "kbm"),)),
    ("UX-209", "ab-shield-absorb", "护盾吃掉了多少伤害", (("ab-shield-absorb", "kbm"),)),
    ("UX-210", "ab-stack-detonate", "叠层再引爆", (("ab-stack-detonate", "kbm"),)),
    ("UX-211", "ab-reflect-back", "我的技能被弹回来", (("ab-reflect-back", "kbm"),)),
    # ---- 技能打在效果和技能身上 ----
    ("UX-212", "ab-target-existing-effect", "目标是身上那条状态", (("ab-target-existing-effect", "kbm"),)),
    ("UX-213", "ab-target-own-ability", "目标是我自己的另一个技能", (("ab-target-own-ability", "kbm"),)),
    ("UX-214", "ab-target-projectile", "目标是飞在空中那颗", (("ab-target-projectile", "kbm"),)),
    ("UX-215", "ab-target-own-summon", "目标是我自己放下的东西", (("ab-target-own-summon", "kbm"),)),
    # ---- 技能被改写 ----
    ("UX-216", "ab-talent-variant", "同一键因天赋结果不同", (("ab-talent-variant", "kbm"),)),
    ("UX-217", "ab-element-reaction", "两种元素凑出额外反应", (("ab-element-reaction", "kbm"),)),
    ("UX-218", "ab-terrain-shape", "技能改的是地形本身", (("ab-terrain-shape", "kbm"),)),
    ("UX-219", "ab-conditional-target", "目标是所有满足条件的", (("ab-conditional-target", "kbm"),)),
]


def iter_case_platform():
    """Yield (case_id, actionNo, actionKey, actionTitle, platform)."""
    for action_no, key, title, members in ACTION_GROUPS:
        for case_id, platform in members:
            yield case_id, action_no, key, title, platform

