param(
    [string]$OutputDirectory = (Join-Path (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path "artifacts\acceptance\item-system-showcase\room-screenshots"),
    [int]$ScreenshotFrame = 180,
    [int]$KillAfterSeconds = 35
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$captureScript = Join-Path $repoRoot "scripts\acceptance\run-item-system-showcase-raylib.ps1"

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

$rooms = @(
    @{ Name = "loadout-garage"; MapId = "item_system_showcase_loadout_garage"; Title = "Loadout Garage" },
    @{ Name = "weapon-bench"; MapId = "item_system_showcase_weapon_bench"; Title = "Weapon Bench" },
    @{ Name = "forge-socket-lab"; MapId = "item_system_showcase_forge_socket_lab"; Title = "Forge & Socket Lab" },
    @{ Name = "raid-loop"; MapId = "item_system_showcase_raid_loop"; Title = "Raid Loop" }
)

$indexLines = New-Object System.Collections.Generic.List[string]
$indexLines.Add("# Item System Showcase Room Screenshots")
$indexLines.Add("")
$indexLines.Add("Generated by `scripts/acceptance/capture-item-system-showcase-rooms.ps1`.")
$indexLines.Add("")

foreach ($room in $rooms) {
    $screenshotPath = Join-Path $OutputDirectory ($room.Name + ".png")
    $diagnosticPath = Join-Path $OutputDirectory ($room.Name + ".log")

    & powershell -NoProfile -ExecutionPolicy Bypass -File $captureScript `
        -ScreenshotPath $screenshotPath `
        -DiagnosticPath $diagnosticPath `
        -ScreenshotFrame $ScreenshotFrame `
        -KillAfterSeconds $KillAfterSeconds `
        -StartupMapId $room.MapId
    if ($LASTEXITCODE -ne 0) {
        throw "Room capture for $($room.MapId) failed with exit code $LASTEXITCODE."
    }

    $indexLines.Add("## $($room.Title)")
    $indexLines.Add("")
    $indexLines.Add("* map: " + $room.MapId)
    $indexLines.Add("* screenshot: " + $screenshotPath)
    $indexLines.Add("* diagnostic: " + $diagnosticPath)
    $indexLines.Add("")
}

$indexPath = Join-Path $OutputDirectory "README.md"
$indexLines | Set-Content $indexPath -Encoding utf8
Write-Output $indexPath
