<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Core\Ludots.Core.csproj" />
    <ProjectReference Include="..\..\..\..\src\Libraries\Ludots.UI\Ludots.UI.csproj" />
    <ProjectReference Include="..\..\..\..\src\Libraries\Ludots.UI.Browser\Ludots.UI.Browser.csproj" />
    <ProjectReference Include="..\..\..\..\src\Libraries\Ludots.WebUI.Browser\Ludots.WebUI.Browser.csproj" />
    <ProjectReference Include="..\..\..\..\src\Libraries\Ludots.WebUI.DataPlane\Ludots.WebUI.DataPlane.csproj" />
    <ProjectReference Include="..\..\..\UiShowcaseCoreMod\UiShowcaseCoreMod.csproj" />
    <ProjectReference Include="..\..\panel_fireball_shared\FireballSharedMod\FireballSharedMod.csproj" />
  </ItemGroup>
</Project>
